import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import { EventEmitter } from 'node:events';
import { HttpError } from 'builder-util-runtime';
import { createRequire } from 'node:module';
import { parse, stringify } from 'yaml';
import { createUpdateGate } from '../../core/update-gate.mjs';
import { createMessageQueue } from '../../core/message-queue.mjs';
import { ensureDataSchema } from '../../core/data-schema.mjs';
import { readSessions } from '../lib/data-store.mjs';
import { prepareArtifacts } from '../../scripts/release-artifacts.mjs';
import { generateReleaseInfo, compareVersions } from '../../scripts/release-info.mjs';
const { Updates } = createRequire(import.meta.url)('../../desktop/updates.cjs');
const { releaseSigning } = createRequire(import.meta.url)('../../scripts/release-signing.cjs');
const { AppUpdater } = createRequire(import.meta.url)('electron-updater/out/AppUpdater.js');
const { GitHubProvider } = createRequire(import.meta.url)('electron-updater/out/providers/GitHubProvider.js');
const { PrivateGitHubProvider } = createRequire(import.meta.url)('electron-updater/out/providers/PrivateGitHubProvider.js');
const { resolveGitHubToken, prepareUpdateCheck } = createRequire(import.meta.url)('../../desktop/update-auth.cjs');
const { createUpdateLog } = createRequire(import.meta.url)('../../desktop/update-log.cjs');
const { t: tr } = createRequire(import.meta.url)('../../desktop/i18n.cjs');
export const name = 'desktop-updates';
export const title = 'Desktop update state, persistence, release integrity and safe shutdown';
export default async function(t) {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'ply-update-test-'));
  const rejects = async (label, action) => { try { await action(); t.ok(label, false); } catch { t.ok(label, true); } };
  try {
    class FakeUpdater extends EventEmitter {
      checks = 0; downloads = 0; latest = '0.2.0';
      async checkForUpdates() { this.checks++; if (this.fail) throw this.failure ?? new Error('network'); this.emit('update-available', { version: this.latest, releaseNotes: '<script>untrusted()</script>' }); }
      async downloadUpdate() { this.downloads++; this.emit('download-progress', { percent: 51 }); this.emit('update-downloaded'); }
    }
    const updater = new FakeUpdater(); let installed = 0, blocked = false;
    const real = new AppUpdater(undefined, { version: '0.2.0-beta.1', userDataPath: dir, whenReady: async () => {} });
    real.logger = null;
    real.stagingUserIdPromise = { value: Promise.resolve('00000000-0000-4000-8000-000080000000') };
    real.channel = 'latest'; real.allowDowngrade = false; real.allowPrerelease = false;
    t.ok('Real updater does not downgrade beta to older stable', !await real.isUpdateAvailable({ version: '0.1.0' }));
    t.ok('Real updater accepts newer stable', await real.isUpdateAvailable({ version: '0.2.0' }));
    t.ok('Real staged rollout excludes zero and includes 100%', !await real.isUpdateAvailable({ version: '0.3.0', stagingPercentage: 0 }) && await real.isUpdateAvailable({ version: '0.3.0', stagingPercentage: 100 }));
    t.ok('Real staged rollout keeps a stable cohort', !await real.isUpdateAvailable({ version: '0.3.0', stagingPercentage: 10 }) && await real.isUpdateAvailable({ version: '0.3.0', stagingPercentage: 90 }));
    const executor = { request: async options => {
      if (options.path.endsWith('.atom')) return '<feed>' + ['0.3.0-beta.1','0.2.0'].map(v => `<entry><title>${v}</title><link href="https://github.com/example/releases/tag/v${v}"/><content>Notes</content></entry>`).join('') + '</feed>';
      if (options.path.endsWith('/latest')) return JSON.stringify({ tag_name: 'v0.2.0' });
      return stringify({ version: options.path.includes('v0.3.0-beta.1') ? '0.3.0-beta.1' : '0.2.0', files: [{url:'Pleiad.exe',sha512:'hash'}] });
    } };
    const provider = new GitHubProvider({owner:'example',repo:'releases'}, real, {platform:'win32',executor});
    t.ok('Real GitHub provider excludes beta for stable channel', (await provider.getLatestVersion()).version === '0.2.0');
    real.channel = 'beta'; real.allowPrerelease = true; real.allowDowngrade = false;
    t.ok('Real GitHub provider selects opted-in beta', (await provider.getLatestVersion()).version === '0.3.0-beta.1');
    let cliCalls = 0;
    const authOptions = { env: {}, platform: 'linux', run: async (_command, args, options) => {
      cliCalls++;
      t.ok('Credential lookup uses GitHub CLI without a shell or visible window', args.join(' ') === 'auth token --hostname github.com' && options.windowsHide && options.timeout === 10000);
      return { stdout: 'test-private-token\n' };
    } };
    t.ok('Existing environment credential has priority', await resolveGitHubToken({ ...authOptions, env: { GH_TOKEN: 'env-token' } }) === 'env-token' && cliCalls === 0);
    const configFile = path.join(dir, 'app-update.yml');
    const configText = stringify({ provider: 'github', owner: 'tekalu1', repo: 'ply', private: true, channel: 'latest' });
    await fs.writeFile(configFile, configText);
    let feed;
    const feedUpdater = { setFeedURL(value) { feed = value; } };
    await prepareUpdateCheck(feedUpdater, configFile, authOptions);
    t.ok('Private provider receives credentials only in memory', feed.private && feed.token === 'test-private-token' && await fs.readFile(configFile, 'utf8') === configText);
    t.ok('Check reports it is authenticated without exposing the token', JSON.stringify(await prepareUpdateCheck(feedUpdater, configFile, { ...authOptions, env: { GH_TOKEN: 'env-token' } })) === '{"authenticated":true}');
    await prepareUpdateCheck(feedUpdater, configFile, authOptions);
    t.ok('Retry reloads CLI authentication', cliCalls === 2);
    // 認証が無くても止めない（配布先は public）。CLI の生のエラーは握りつぶして外へ出さない
    const noAuthOptions = { env: {}, platform: 'linux', run: async () => { throw new Error('secret-output'); } };
    t.ok('Missing authentication resolves to no token instead of failing', await resolveGitHubToken(noAuthOptions) === null);
    t.ok('Blank environment credential is ignored', await resolveGitHubToken({ ...noAuthOptions, env: { GH_TOKEN: '  ', GITHUB_TOKEN: '' } }) === null);
    let anonymousFeed;
    const anonymousResult = await prepareUpdateCheck({ setFeedURL(value) { anonymousFeed = value; } }, configFile, noAuthOptions);
    t.ok('Update check proceeds without a token using the same newest-release provider', anonymousResult.authenticated === false && !anonymousFeed.token && anonymousFeed.provider === 'custom' && typeof anonymousFeed.updateProvider === 'function' && await fs.readFile(configFile, 'utf8') === configText);
    await fs.writeFile(configFile, stringify({ ...parse(configText), host: 'unexpected.example' }));
    await rejects('Credentials cannot go to an unexpected host', () => prepareUpdateCheck(feedUpdater, configFile, authOptions));
    t.ok('Unsupported host is rejected before credential lookup', cliCalls === 2);
    const privateRequests = [];
    const release = (version, prerelease) => ({ tag_name: `v${version}`, prerelease, draft: false, assets: [
      { name: 'latest.yml', url: `https://api.github.com/assets/${version}/metadata` },
      { name: 'Pleiad.exe', url: `https://api.github.com/assets/${version}/installer` },
    ] });
    const privateProvider = new PrivateGitHubProvider(feed, real, 'test-private-token', { platform: 'win32', executor: { request: async options => {
      privateRequests.push(options);
      if (options.path.endsWith('/releases/latest')) return JSON.stringify(release('0.2.0', false));
      if (options.path.endsWith('/releases')) return JSON.stringify([{ ...release('0.4.0-beta.1', true), draft: true }, release('0.3.0-beta.1', true), release('0.2.0', false)]);
      return stringify({ version: options.path.includes('0.3.0') ? '0.3.0-beta.1' : '0.2.0', files: [{ url: 'Pleiad.exe', sha512: 'hash' }] });
    } } });
    const privateBeta = await privateProvider.getLatestVersion();
    t.ok('Private beta uses latest.yml and skips drafts', privateBeta.version === '0.3.0-beta.1' && privateProvider.resolveFiles(privateBeta)[0].url.pathname.endsWith('/installer'));
    real.channel = 'latest'; real.allowPrerelease = false; real.allowDowngrade = false;
    t.ok('Private stable excludes prereleases', (await privateProvider.getLatestVersion()).version === '0.2.0');
    t.ok('Private metadata and downloads carry authentication', privateRequests.every(r => r.headers.authorization === 'token test-private-token') && privateProvider.fileExtraDownloadHeaders.authorization === 'token test-private-token');
    // GitHub lists releases by tag text, so beta.9 comes before beta.11 and beta.10.
    const listed = ['0.1.0-beta.9', '0.1.0-beta.8', '0.1.0-beta.11', '0.1.0-beta.10'].map(v => release(v, true));
    const newestProvider = new feed.updateProvider(feed, real, { platform: 'win32', executor: { request: async options => {
      if (options.path.includes('/releases?')) return JSON.stringify([{ ...release('0.1.0-beta.12', true), draft: true }, ...listed]);
      return stringify({ version: options.path.match(/assets\/([^/]+)/)[1], files: [{ url: 'Pleiad.exe', sha512: 'hash' }] });
    } } });
    real.channel = 'beta'; real.allowPrerelease = true;
    const newest = await newestProvider.getLatestVersion();
    t.ok('Beta picks the newest version rather than the first listed', newest.version === '0.1.0-beta.11' && newestProvider.resolveFiles(newest)[0].url.pathname.endsWith('/installer'));
    t.ok('Newest-version provider downloads from the public release without the token', JSON.stringify(newestProvider.fileExtraDownloadHeaders) === '{"accept":"application/octet-stream"}');
    // インストーラーは公開の配布の URL（名前入り）から取る。API の資産の URL（番号）では CPU に合うものを選べず、
    // 一覧の先頭の両方入りを取り、blockmap の URL も作れずに差分の取得が毎回失敗していた（0.8.0）
    const { findFile } = createRequire(import.meta.url)('electron-updater/out/providers/Provider.js');
    const download = name => `https://github.com/tekalu1/pleiad/releases/download/v0.8.1/${name}`;
    const archRelease = { version: '0.8.1', files: ['Pleiad-0.8.1-win.exe', 'Pleiad-0.8.1-win-x64.exe', 'Pleiad-0.8.1-win-arm64.exe'].map(url => ({ url, sha512: 'hash', size: 1 })), path: 'Pleiad-0.8.1-win.exe', sha512: 'hash',
      assets: ['Pleiad-0.8.1-win.exe', 'Pleiad-0.8.1-win-x64.exe', 'Pleiad-0.8.1-win-arm64.exe'].map((name, i) => ({ name, url: `https://api.github.com/repos/tekalu1/pleiad/releases/assets/${i + 1}`, browser_download_url: download(name) })) };
    const archFiles = newestProvider.resolveFiles(archRelease);
    const ownArch = findFile(archFiles, 'exe');
    t.ok('The installer for this CPU is chosen, not the combined one listed first', ownArch.url.href === download(`Pleiad-0.8.1-win-${process.arch}.exe`) || !['x64', 'arm64'].includes(process.arch));
    const ownInstaller = new URL(download(`Pleiad-0.8.1-win-${process.arch}.exe`));
    const previous = name => `https://github.com/tekalu1/pleiad/releases/download/v0.8.0/${name}`;
    const [oldBlockMap, newBlockMap] = await newestProvider.getBlockMapFiles(ownInstaller, '0.8.0', '0.8.1');
    t.ok('Block maps for the differential download point at both releases', newBlockMap.href === `${ownInstaller.href}.blockmap`
      && oldBlockMap.href === previous(`Pleiad-0.8.0-win-${process.arch}.exe.blockmap`));
    // 0.8.0 までは両方入りを取って手元に残していた。それが残っていれば、前の版の blockmap も両方入りのものと組む
    const cacheDir = path.join(dir, 'updater-cache');
    await fs.mkdir(cacheDir, { recursive: true });
    real.downloadedUpdateHelper = { cacheDir };
    await fs.writeFile(path.join(cacheDir, 'installer.exe'), 'xx');
    t.ok('A cached combined installer is paired with the combined block map of the previous release', (await newestProvider.getBlockMapFiles(ownInstaller, '0.8.0', '0.8.1'))[0].href === previous('Pleiad-0.8.0-win.exe.blockmap'));
    await fs.writeFile(path.join(cacheDir, 'installer.exe'), 'x');
    t.ok('A cached installer for this CPU keeps the block map for this CPU', (await newestProvider.getBlockMapFiles(ownInstaller, '0.8.0', '0.8.1'))[0].href === previous(`Pleiad-0.8.0-win-${process.arch}.exe.blockmap`));
    real.downloadedUpdateHelper = null;
    t.ok('Differential ranges are requested one at a time (GitHub answers multi-range requests with 501)', newestProvider.isUseMultipleRangeRequest === false);
    t.ok('Assets without a public URL keep the API URL', newestProvider.resolveFiles({ ...archRelease, assets: archRelease.assets.map(({ browser_download_url, ...a }) => a) })[1].url.href.endsWith('/assets/2'));
    // トークン無し: 同じプロバイダーで、どの要求にも authorization を付けない
    const anonymousRequests = [];
    const anonymousProvider = new anonymousFeed.updateProvider(anonymousFeed, real, { platform: 'win32', executor: { request: async options => {
      anonymousRequests.push(options);
      if (options.path.includes('/releases?')) return JSON.stringify([{ ...release('0.1.0-beta.12', true), draft: true }, ...listed]);
      if (options.path.endsWith('/releases/latest')) return JSON.stringify(release('0.2.0', false));
      return stringify({ version: options.path.match(/assets\/([^/]+)/)[1], files: [{ url: 'Pleiad.exe', sha512: 'hash' }] });
    } } });
    real.channel = 'beta'; real.allowPrerelease = true;
    const anonymousNewest = await anonymousProvider.getLatestVersion();
    t.ok('Without a token the newest version is still chosen and files resolve', anonymousNewest.version === '0.1.0-beta.11' && anonymousProvider.resolveFiles(anonymousNewest)[0].url.pathname.endsWith('/installer'));
    real.channel = 'latest'; real.allowPrerelease = false;
    t.ok('Without a token the stable channel uses the latest release', (await anonymousProvider.getLatestVersion()).version === '0.2.0');
    t.ok('Without a token no request carries an authorization header', anonymousRequests.length >= 4 && anonymousRequests.every(r => !Object.keys(r.headers).some(k => k.toLowerCase() === 'authorization') && r.headers.accept));
    t.ok('Without a token downloads ask for the raw asset and carry no authorization', JSON.stringify(anonymousProvider.fileExtraDownloadHeaders) === '{"accept":"application/octet-stream"}');
    real.channel = 'latest'; real.allowPrerelease = false;
    t.ok('Stable-channel HTTP failures keep their status code so the error text can tell them apart', await new anonymousFeed.updateProvider(anonymousFeed, real, { platform: 'win32', executor: { request: async () => { throw new HttpError(429); } } }).getLatestVersion().then(() => 0, e => e.statusCode) === 429);
    // 更新の記録: トークン・authorization・署名付きの URL の問い合わせ部分は伏せ、大きくなったら 1 世代だけ残す
    const updateLogFile = path.join(dir, 'logs', 'updater.log');
    const updateLog = createUpdateLog(updateLogFile);
    updateLog.info('Download block maps (old: "https://github.com/o/r/releases/download/v1/a.blockmap", new: https://release-assets.githubusercontent.com/x/1?sig=SECRETSIG&jwt=SECRETJWT)');
    updateLog.error(new Error('HttpError: 401 headers {"authorization":"token gho_0123456789abcdefghijABCDEFGHIJ"} Bearer abcdefghijklmnopqrstuvwxyz'));
    updateLog.warn('github_pat_0123456789abcdefghijklmnop leaked');
    await updateLog.flush();
    const logged = await fs.readFile(updateLogFile, 'utf8');
    t.ok('Update log keeps the useful text', logged.includes('Download block maps') && logged.includes('releases/download/v1/a.blockmap') && logged.includes('release-assets.githubusercontent.com/x/1?[redacted]'));
    t.ok('Update log hides tokens and signed URL keys', !/SECRETSIG|SECRETJWT|gho_|github_pat_|abcdefghijklmnopqrstuvwxyz/.test(logged));
    const rotatingFile = path.join(dir, 'logs', 'rotating.log');
    const rotating = createUpdateLog(rotatingFile, { maxBytes: 100 });
    rotating.info('a'.repeat(150));
    rotating.info('second');
    await rotating.flush();
    t.ok('Update log rotates once it grows past its limit', (await fs.readFile(`${rotatingFile}.old`, 'utf8')).includes('aaaa') && (await fs.readFile(rotatingFile, 'utf8')).trim().endsWith('info second'));
    real.channel = 'latest'; real.allowPrerelease = false;
    const file = path.join(dir, 'updates.json');
    const make = version => new Updates({ updater, version, file, enabled: true, install: async () => { if (blocked) throw new Error('Busy'); installed++; } });
    const controller = make('0.1.0'); await controller.init();
    t.ok('First install does not announce an upgrade', !controller.snapshot().notice);
    t.ok('New installs prepare updates automatically but never auto-install', controller.snapshot().autoDownload && !updater.autoInstallOnAppQuit);
    await controller.command('preferences', { channel: 'stable', autoDownload: false, autoCheck: true });
    const manual = new Updates({ updater: new FakeUpdater(), version: '0.1.0', file, enabled: true, install: async () => {} });
    await manual.init();
    t.ok('Existing manual-download choice is preserved', !manual.snapshot().autoDownload);
    t.ok('Stable defaults and explicit install', updater.channel === 'latest' && !updater.allowPrerelease && !updater.allowDowngrade && !updater.autoDownload && !updater.autoInstallOnAppQuit);
    await rejects('Cannot install before downloading', () => controller.command('install'));
    await controller.command('check');
    t.ok('Successful checks expose their time', Number.isFinite(Date.parse(controller.snapshot().lastChecked)));
    t.ok('Check does not download without consent', controller.snapshot().phase === 'available' && updater.downloads === 0);
    await controller.command('download');
    t.ok('Download never installs', controller.snapshot().phase === 'downloaded' && installed === 0);
    await rejects('Downloaded update cannot switch channels', () => controller.command('preferences', { channel: 'beta', autoDownload: true, autoCheck: true }));
    const checks = updater.checks; await controller.command('check');
    t.ok('Periodic check preserves downloaded update', updater.checks === checks + 1 && controller.snapshot().phase === 'downloaded' && controller.snapshot().target === '0.2.0');
    updater.fail = true; await controller.command('check'); updater.fail = false;
    t.ok('Failed recheck keeps the downloaded update installable', controller.snapshot().phase === 'downloaded' && controller.snapshot().target === '0.2.0' && !controller.snapshot().error);
    blocked = true;
    await rejects('Work blocks installation', () => controller.command('install'));
    t.ok('Blocked install remains retryable', controller.snapshot().phase === 'downloaded' && installed === 0);
    blocked = false; await controller.command('install');
    t.ok('Explicit install calls lifecycle once', installed === 1);
    const next = make('0.2.0'); await next.init();
    t.ok('Upgrade has one launch notice', next.snapshot().notice);
    const reloaded = make('0.2.0'); await reloaded.init();
    t.ok('Same version next launch has no notice', !reloaded.snapshot().notice);
    await reloaded.command('preferences', { channel: 'beta', autoDownload: true, autoCheck: false });
    t.ok('Beta opt-in never enables downgrade', updater.channel === 'beta' && updater.allowPrerelease && !updater.allowDowngrade);
    class QuietUpdater extends EventEmitter { checks = 0; async checkForUpdates() { this.checks++; this.emit(this.latest ? 'update-available' : 'update-not-available', { version: this.latest }); } async downloadUpdate() {} }
    const quiet = new QuietUpdater();
    const timed = new Updates({ updater: quiet, version: '0.1.0', file: path.join(dir, 'auto.json'), enabled: true, install: async () => {} });
    await timed.init();
    await timed.command('preferences', { channel: 'stable', autoDownload: false, autoCheck: true });
    t.ok('Automatic check runs when none has run yet', await timed.auto(60_000) && quiet.checks === 1);
    t.ok('Automatic check waits for the minimum gap, manual checks included', !await timed.auto(60_000) && quiet.checks === 1);
    timed.lastAttempt = Date.now() - 61_000;
    t.ok('Automatic check runs again once the gap has passed', await timed.auto(60_000) && quiet.checks === 2);
    quiet.latest = '0.2.0'; await timed.auto();
    t.ok('Automatic check leaves an offered update alone', timed.snapshot().phase === 'available' && !await timed.auto() && quiet.checks === 3);
    await timed.command('preferences', { channel: 'stable', autoDownload: false, autoCheck: false });
    t.ok('Automatic check respects the opt-out', !await timed.auto() && quiet.checks === 3);
    const persisted = make('0.2.0'); await persisted.init();
    t.ok('Manual checks and download preference persist', !persisted.snapshot().autoCheck && persisted.snapshot().autoDownload);
    await persisted.command('check');
    t.ok('Opted-in automatic download runs after check', updater.downloads === 2 && persisted.snapshot().phase === 'downloaded');
    const offline = make('0.2.0'); await offline.init(); updater.fail = true;
    await rejects('Network error propagates', () => offline.command('check'));
    t.ok('Network failure is recoverable', offline.snapshot().phase === 'error');
    updater.fail = false; await offline.command('check');
    t.ok('Retry succeeds', offline.snapshot().phase === 'downloaded');
    const downloadsBeforeNewer = updater.downloads; updater.latest = '0.3.0';
    await offline.command('check');
    t.ok('A newer release replaces the downloaded one', offline.snapshot().phase === 'downloaded' && offline.snapshot().target === '0.3.0' && updater.downloads === downloadsBeforeNewer + 1);
    offline.state.autoDownload = false; updater.latest = '0.4.0';
    await offline.command('check');
    t.ok('Without automatic download a newer release is offered', offline.snapshot().phase === 'available' && offline.snapshot().target === '0.4.0' && updater.downloads === downloadsBeforeNewer + 1);
    updater.latest = '0.2.0';
    // 認証なしでも確認は進む。失敗の文は、トークンを付けたかと HTTP の状態コードで分ける
    let authenticated = false;
    const privateController = new Updates({ updater, version: '0.2.0', file, enabled: true, install: async () => {}, prepareCheck: async () => ({ authenticated }) });
    privateController.state.autoDownload = false;
    const checksBeforeAuth = updater.checks;
    await privateController.command('check');
    t.ok('A check without any credential is sent and succeeds', privateController.snapshot().phase === 'available' && updater.checks === checksBeforeAuth + 1 && !privateController.snapshot().error);
    const failWith = async (controller, status) => {
      updater.fail = true; updater.failure = Object.assign(new Error('secret request detail'), { statusCode: status });
      try { await rejects('Failed check surfaces as an error', () => controller.command('check')); } finally { updater.fail = false; updater.failure = null; }
      return controller.snapshot().error;
    };
    const anonymousLimit = await failWith(privateController, 403);
    t.ok('Unauthenticated 403 explains the rate limit and suggests gh auth login', anonymousLimit === tr('update.rateLimited') && anonymousLimit.includes('gh auth login') && anonymousLimit.includes('60'));
    t.ok('Unauthenticated 429 is also the rate limit', await failWith(privateController, 429) === tr('update.rateLimited'));
    t.ok('Unauthenticated 404 is not presented as an authentication problem', await failWith(privateController, 404) === tr('update.networkFailed'));
    authenticated = true; await privateController.command('check');
    t.ok('Authenticated check works and keeps the token out of state', privateController.snapshot().phase === 'available' && !JSON.stringify(privateController.snapshot()).includes('test-private-token'));
    for (const status of [401, 403]) t.ok(`Authenticated ${status} points at the credential`, await failWith(privateController, status) === tr('update.authFailed'));
    t.ok('Authenticated 404 (for example no stable release yet) is not blamed on the credential', await failWith(privateController, 404) === tr('update.networkFailed'));
    const authenticatedLimit = await failWith(privateController, 429);
    t.ok('Authenticated 429 is a plain rate limit without the login hint', authenticatedLimit === tr('update.rateLimitedAuth') && !authenticatedLimit.includes('gh auth login'));
    t.ok('Error text never carries raw request details', !JSON.stringify(privateController.snapshot()).includes('secret request detail'));
    const corruptUpdater = new FakeUpdater();
    corruptUpdater.downloadUpdate = async () => {
      const error = Object.assign(new Error('private request secret'), { code: 'ERR_UPDATER_INVALID_SIGNATURE' });
      corruptUpdater.emit('error', error); throw error;
    };
    let corruptInstalled = false;
    const corrupt = new Updates({ updater: corruptUpdater, version: '0.1.0', file, enabled: true, install: async () => { corruptInstalled = true; } });
    await rejects('Invalid signature prevents an automatic update', () => corrupt.command('check'));
    t.ok('Signature failure is distinct and hides raw errors', corrupt.snapshot().error.includes('安全性') && !corrupt.snapshot().error.includes('secret') && !corruptInstalled);
    await rejects('An invalid update cannot be installed', () => corrupt.command('install'));
    const publisher = { PLY_WIN_PUBLISHER: 'Example Publisher' };
    await rejects('Signing refuses missing credentials', async () => releaseSigning(publisher, 'win32'));
    const pfx = releaseSigning({ ...publisher, CSC_LINK: 'private-key', CSC_KEY_PASSWORD: 'private-password' }, 'win32');
    t.ok('Signing pins updater verification to the publisher and does not embed keys', pfx.win.verifyUpdateCodeSignature && pfx.win.signtoolOptions.publisherName === publisher.PLY_WIN_PUBLISHER && !JSON.stringify(pfx).includes('private-'));
    const store = releaseSigning({ ...publisher, PLY_WINDOWS_SIGNING: 'store', PLY_WIN_CERTIFICATE_SHA1: 'a'.repeat(40) }, 'win32');
    t.ok('Hardware-backed Windows store certificate does not require key export', store.win.signtoolOptions.certificateSha1 === 'a'.repeat(40));
    const azureEnv = { ...publisher, PLY_WINDOWS_SIGNING: 'azure', PLY_AZURE_ENDPOINT: 'https://eus.codesigning.azure.net/', PLY_AZURE_ACCOUNT: 'account', PLY_AZURE_PROFILE: 'profile', AZURE_TENANT_ID: 'tenant', AZURE_CLIENT_ID: 'client', AZURE_CLIENT_SECRET: 'azure-secret' };
    const azure = releaseSigning(azureEnv, 'win32');
    t.ok('Cloud signing preserves publisher verification without embedding authentication', azure.win.azureSignOptions.publisherName === publisher.PLY_WIN_PUBLISHER && !JSON.stringify(azure).includes('azure-secret') && !azure.win.signtoolOptions);
    await rejects('Signing refuses unrecognized methods', async () => releaseSigning({ ...publisher, PLY_WINDOWS_SIGNING: 'skip' }, 'win32'));
    await rejects('Signing refuses unexpected cloud endpoints', async () => releaseSigning({ ...azureEnv, PLY_AZURE_ENDPOINT: 'https://example.com' }, 'win32'));
    await rejects('macOS release requires notarization credentials', async () => releaseSigning({ CSC_LINK: 'key', CSC_KEY_PASSWORD: 'password' }, 'darwin'));
    const gate = createUpdateGate(), leave = gate.enter();
    t.ok('Active login/save blocks shutdown lease', !gate.acquire());
    leave(); leave();
    t.ok('Permissions and pending work block lease', !gate.acquire(true));
    t.ok('Idle acquires lease', gate.acquire());
    await rejects('Lease rejects racing new work', () => gate.enter());
    gate.release(); const finish = gate.enter(); finish();
    t.ok('Failed install unlocks work', gate.acquire()); gate.release();
    let resolveQueue;
    const pendingQueue = new Promise(resolve => { resolveQueue = resolve; });
    const queue = createMessageQueue({ store: { get: () => pendingQueue } });
    const read = queue.list('session');
    t.ok('Queue work blocks updates before its first await', queue.busy);
    resolveQueue({ outbox: [] }); await read;
    t.ok('Queue releases update guard after persistence completes', !queue.busy);
    const data = path.join(dir, 'data'); await ensureDataSchema(data);
    t.ok('A new data directory is registered as the current format', JSON.parse(await fs.readFile(path.join(data, 'data-schema.json'), 'utf8')).schema === 2);
    await fs.writeFile(path.join(data, 'data-schema.json'), '{"schema":1}');
    await fs.writeFile(path.join(data, 'sessions.json'), '{"keep":{"title":"kept"}}');
    await ensureDataSchema(data);
    t.ok('Schema upgrade preserves existing sessions (migrated into the database, original kept in the backup)',
      readSessions(data).keep?.title === 'kept' && JSON.parse(await fs.readFile(path.join(data, 'data-schema.json'), 'utf8')).schema === 2
      && (await fs.readdir(data)).some(name => name.startsWith('backup-schema1-')));
    await fs.writeFile(path.join(data, 'data-schema.json'), '{"schema":3}');
    await rejects('Future schema cannot be opened by older app', () => ensureDataSchema(data));
    await fs.writeFile(path.join(data, 'data-schema.json'), '{}');
    await rejects('Malformed schema does not silently reset', () => ensureDataSchema(data));
    const assets = path.join(dir, 'assets'); await fs.mkdir(assets);
    const names = ['Pleiad-win.exe', 'Pleiad-mac-x64.zip', 'Pleiad-mac-arm64.zip', 'Pleiad-mac.dmg'];
    for (const name of names) await fs.writeFile(path.join(assets, name), name);
    const entry = name => ({ url: name, sha512: crypto.createHash('sha512').update(name).digest('base64') });
    await fs.writeFile(path.join(assets, 'latest.yml'), stringify({ version: '0.1.0-beta.1', files: [entry(names[0])] }));
    await fs.writeFile(path.join(assets, 'latest-mac.yml'), stringify({ version: '0.1.0-beta.1', files: names.slice(1).map(entry) }));
    await prepareArtifacts(assets, '0.1.0-beta.1', 10, 'Release notes');
    t.ok('Both platform feeds carry rollout and notes', (await Promise.all(['latest.yml', 'latest-mac.yml'].map(async n => parse(await fs.readFile(path.join(assets, n), 'utf8'))))).every(m => m.stagingPercentage === 10 && m.releaseNotes === 'Release notes'));
    await prepareArtifacts(assets, '0.1.0-beta.1', 0);
    t.ok('Rollout can pause at zero', parse(await fs.readFile(path.join(assets, 'latest.yml'), 'utf8')).stagingPercentage === 0);
    await rejects('Invalid rollout is rejected', () => prepareArtifacts(assets, '0.1.0-beta.1', 101));
    await fs.writeFile(path.join(assets, names[1]), 'tampered');
    await rejects('Tampered package prevents publication', () => prepareArtifacts(assets, '0.1.0-beta.1', 100));
    const windowsAssets = path.join(dir, 'windows-assets'); await fs.mkdir(windowsAssets);
    await fs.writeFile(path.join(windowsAssets, names[0]), names[0]);
    await fs.writeFile(path.join(windowsAssets, 'latest.yml'), stringify({ version: '0.1.0-beta.1', files: [entry(names[0])] }));
    await rejects('Missing macOS assets are not silently treated as Windows-only', () => prepareArtifacts(windowsAssets, '0.1.0-beta.1', 10));
    await fs.writeFile(path.join(windowsAssets, 'Pleiad-Evaluation.cer'), 'public certificate');
    await fs.writeFile(path.join(windowsAssets, 'SIGNING-INFO.json'), '{"privateKeyIncluded":false}');
    await fs.writeFile(path.join(windowsAssets, 'certificate.pfx'), 'private key fixture');
    await prepareArtifacts(windowsAssets, '0.1.0-beta.1', 10, 'Windows update', 'windows');
    const sums = await fs.readFile(path.join(windowsAssets, 'SHA256SUMS.txt'), 'utf8');
    t.ok('Evaluation public certificate is covered by checksums while PFX is excluded', sums.includes('Pleiad-Evaluation.cer') && sums.includes('SIGNING-INFO.json') && !sums.includes('certificate.pfx'));
    await prepareArtifacts(windowsAssets, '0.1.0-beta.1', 50);
    t.ok('Windows-only rollout preserves the selected platform manifest', JSON.parse(await fs.readFile(path.join(windowsAssets, 'RELEASE-PLATFORMS.json'), 'utf8')).platforms === 'windows' && parse(await fs.readFile(path.join(windowsAssets, 'latest.yml'), 'utf8')).stagingPercentage === 50);
    await rejects('Release platform selection cannot change during rollout', () => prepareArtifacts(windowsAssets, '0.1.0-beta.1', 50, null, 'all'));
    await fs.writeFile(path.join(windowsAssets, names[0]), 'changed');
    await rejects('Windows-only releases still reject changed installers', () => prepareArtifacts(windowsAssets, '0.1.0-beta.1', 100));
    await generateReleaseInfo();
    const pkg = JSON.parse(await fs.readFile(new URL('../../package.json', import.meta.url), 'utf8'));
    const info = JSON.parse(await fs.readFile(new URL('../../web/release-info.json', import.meta.url), 'utf8'));
    t.ok('Package and visible version share a source', pkg.version === info.version && info.releases.some(r => r.version === pkg.version));
    const ordered = ['0.1.0-beta.9', '0.2.0', '0.1.0', '0.10.0', '0.1.0-beta.74', '0.2.0-beta.1', '0.1.1'].sort((a, b) => compareVersions(b, a));
    t.ok('Release history is newest first in semver order', ordered.join() === '0.10.0,0.2.0,0.2.0-beta.1,0.1.1,0.1.0,0.1.0-beta.74,0.1.0-beta.9');
  } finally { await fs.rm(dir, { recursive: true, force: true }); }
}
