import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { startServer, ROOT } from '../lib/server.mjs';
import { open } from '../lib/ws-client.mjs';
import { effortOptions, validateEffort } from '../../core/effort.mjs';
export const name = 'effort';
export const title = 'エフォートの検証・予約・保存・引き継ぎ';
export default async function(t) {
  assert.deepEqual(Object.keys(await effortOptions({ id: 'claude' })), ['', 'low', 'medium', 'high', 'xhigh', 'max']);
  const codex = { id: 'codex', models: async () => ({ test: { efforts: ['low', 'high', 'ultra'] } }) };
  assert.deepEqual(Object.keys(await effortOptions(codex, 'test')), ['', 'low', 'high', 'ultra']);
  await assert.rejects(validateEffort(codex, 'max', 'test'));
  t.ok('Codex のモデル固有の候補と Claude の SDK 語彙を使う', true);
  const dataDir = await fs.mkdtemp(path.join(os.tmpdir(), 'ply-effort-'));
  let server, client;
  try {
    server = await startServer({ dataDir, env: { AGENT_HOST_BACKENDS: 'fake' } });
    client = await open({ port: server.port, token: server.token });
    const { sessionId } = await client.cmd('newSession', { backend: 'fake', cwd: ROOT });
    const get = async () => (await client.cmd('listSessions')).find(s => s.id === sessionId);
    await assert.rejects(client.cmd('setTurnSettings', { sessionId, effort: 'invalid' }));
    await client.cmd('setTurnSettings', { sessionId, effort: 'high', rememberEffort: true });
    assert.equal((await get()).effort, '');
    assert.equal((await get()).nextSettings.effort, 'high');
    assert.equal((await client.cmd('prefs')).backends.fake.effort, 'high');
    await client.cmd('setTurnSettings', { sessionId, cwd: ROOT });
    assert.equal((await get()).nextSettings.effort, 'high');
    client.close(); await server.stop();
    server = await startServer({ dataDir, env: { AGENT_HOST_BACKENDS: 'fake' } });
    client = await open({ port: server.port, token: server.token });
    assert.equal((await get()).nextSettings.effort, 'high');
    const turn = await client.runTurn({ sessionId, prompt: 'echo:effort' });
    assert.equal(turn.outcome, 'ok');
    assert.equal((await get()).effort, 'high');
    assert.equal((await get()).nextSettings, null);
    const mark = client.mark();
    await client.cmd('runTurn', { sessionId, prompt: 'slow' });
    await client.cmd('setTurnSettings', { sessionId, effort: 'low' });
    assert.equal((await get()).effort, 'high');
    assert.equal((await client.cmd('running')).turns.find(t => t.sessionId === sessionId).effort, 'high');
    const fork = await client.cmd('fork', { sessionId });
    const forkRow = (await client.cmd('listSessions')).find(s => s.id === fork.sessionId);
    assert.equal(forkRow.effort, 'high');
    assert.equal(forkRow.nextSettings.effort, 'low');
    await client.cmd('abort', { sessionId });
    await client.waitFor(e => e.type === 'turnEnd' && e.sessionId === sessionId, { from: mark });
    await client.cmd('setTurnSettings', { sessionId, cancel: true });
    t.ok('実行中の設定を保ち、分岐に現在値と予約を引き継ぐ', true);
    const child = await client.cmd('newSession', { sourceSessionId: sessionId, cwd: ROOT });
    assert.equal((await client.cmd('listSessions')).find(s => s.id === child.sessionId).effort, 'high');
    await client.cmd('setTurnSettings', { sessionId, effort: 'low' });
    await client.cmd('setTurnSettings', { sessionId, cancel: true });
    assert.equal((await get()).effort, 'high');
    assert.equal((await get()).nextSettings, null);
    await client.cmd('setTurnSettings', { sessionId, effort: '' });
    await client.runTurn({ sessionId, prompt: 'echo:reset' });
    assert.equal((await get()).effort, '');
    t.ok('予約の永続化・適用・引き継ぎ・取り消し・既定への復帰', true);
  } finally { client?.close(); await server?.stop(); await fs.rm(dataDir, { recursive: true, force: true }); }
}
