import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { startServer, ROOT } from '../lib/server.mjs';
import { open } from '../lib/ws-client.mjs';
export const name = 'server-ux';
export const title = '未送信セッションと設定予約が保存され、次のターンだけに適用される';
export default async function(t) {
  const dataDir = await fs.mkdtemp(path.join(os.tmpdir(), 'agent-host-ux-'));
  const config = { dataDir, env: { AGENT_HOST_BACKENDS: 'fake,codex', AGENT_HOST_CODEX_BIN: `node "${path.join(ROOT, 'tests/lib/fake-codex.mjs')}"` } };
  let server = await startServer(config), c = await open({ port: server.port, token: server.token, autoAllow: true });
  const row = async id => (await c.cmd('listSessions')).find(s => s.id === id);
  try {
    const { sessionId: autoId } = await c.cmd('newSession', { backend: 'codex', cwd: ROOT });
    await c.runTurn({ sessionId: autoId, prompt: 'initial title request' });
    t.ok('Codex 初回送信で仮タイトルをネイティブのタイトルに置き換える', (await row(autoId)).title === 'fake thread');
    await c.cmd('setTitle', { sessionId: autoId, title: '新しいセッション' });
    await c.runTurn({ sessionId: autoId, prompt: 'later request' });
    t.ok('仮タイトルと同じ名前でも明示的な命名を保持する', (await row(autoId)).title === '新しいセッション');
    const { sessionId: id } = await c.cmd('newSession', { backend: 'fake', cwd: ROOT, status: '作業中' });
    t.ok('送信前にIDと一覧が保存される', Boolean(id) && (await row(id)).unsent && (await row(id)).status === '作業中');
    await c.cmd('setTitle', { sessionId: id, title: '入力中の会話' });
    await c.cmd('saveDraft', { sessionId: id, text: '書きかけ', attached: [{ name: 'memo.txt', path: path.join(ROOT, 'package.json'), kind: 'file' }] });
    await c.cmd('setTurnSettings', { sessionId: id, backend: 'fake', model: 'fast', rememberModel: true });
    t.ok('明示的なモデル選択をエージェント別の新規既定にも保存', (await c.cmd('prefs')).backends?.fake?.model === 'fast');
    const draft = (await c.cmd('loadSession', { sessionId: id })).draft;
    c.close(); await server.stop(); server = await startServer(config); c = await open({ port: server.port, token: server.token, autoAllow: true });
    t.ok('未送信セッション・名前が再起動後にも残る', (await row(id)).title === '入力中の会話');
    t.ok('本文と添付の下書きを復元', JSON.stringify((await c.cmd('loadSession', { sessionId: id })).draft) === JSON.stringify(draft));
    t.ok('次ターン設定も復元', (await row(id)).nextSettings?.model === 'fast' && (await row(id)).model === '');
    const first = await c.runTurn({ sessionId: id, prompt: 'echo:first' });
    t.ok('初回送信でもホストIDは変わらない', first.events.filter(e => e.sessionId).every(e => e.sessionId === id));
    t.ok('送信前に付けたタイトルを初回実行でも保持', (await row(id)).title === '入力中の会話');
    t.ok('初回に予約モデルを使用', first.initModel === 'fast' && !(await row(id)).unsent && !(await row(id)).nextSettings);
    t.ok('空のホスト会話に余計な引き継ぎ文を入れない', (await c.cmd('loadSession', { sessionId: id })).messages[0].text === 'echo:first');
    const mark = c.mark();
    await c.cmd('runTurn', { sessionId: id, prompt: 'slow' });
    await c.cmd('setTurnSettings', { sessionId: id, backend: 'codex', model: 'fake-model-2' });
    const originalMode = (await row(id)).mode;
    await c.cmd('setTurnSettings', { sessionId: id, mode: 'readonly', rememberMode: true });
    t.ok('変更先の承認モードを予約し、実行中の承認モードは保持', (await row(id)).nextSettings?.mode === 'readonly' && (await row(id)).mode === originalMode);
    await c.cmd('setTurnSettings', { sessionId: id, mode: 'default' }).then(() => t.ok('変更前だけの承認モードは拒否', false), () => t.ok('変更前だけの承認モードは拒否', true));
    t.ok('不正なモード変更は予約を壊さない', (await row(id)).nextSettings?.mode === 'readonly');
    await c.cmd('setTurnSettings', { sessionId: id, model: 'fake-model-2' });
    t.ok('モデル変更でも承認モード予約を保持', (await row(id)).nextSettings?.mode === 'readonly');
    let live = (await c.cmd('running')).turns.find(t => t.sessionId === id);
    t.ok('実行中のエージェントとモデルは変わらない', live.backend === 'fake' && live.model === 'fast');
    await c.cmd('setTurnSettings', { sessionId: id, cancel: true });
    t.ok('予約を取り消せる', !(await row(id)).nextSettings);
    await c.cmd('setTurnSettings', { sessionId: id, backend: 'codex', model: 'fake-model-2' });
    await c.cmd('abort', { sessionId: id }); await c.waitFor(e => e.type === 'turnEnd', { from: mark });
    t.ok('完了しても次の送信まで予約を保持', (await row(id)).backend === 'fake' && (await row(id)).nextSettings?.backend === 'codex');
    await c.cmd('runTurn', { sessionId: id, cwd: path.join(dataDir, 'missing'), prompt: 'bad' }).then(() => t.ok('無効な作業場所を拒否', false), () => t.ok('無効な作業場所を拒否', true));
    t.ok('送信準備失敗でも予約と元の実行先を維持', (await row(id)).backend === 'fake' && (await row(id)).nextSettings?.model === 'fake-model-2');
    const second = await c.runTurn({ sessionId: id, prompt: 'continue' });
    t.ok('次のターンでエージェントとモデルを適用', second.initModel === 'fake-model-2' && (await row(id)).backend === 'codex' && !(await row(id)).nextSettings);
    t.ok('次のターンで変更先の承認モードを適用', (await row(id)).mode === 'readonly');
    t.ok('履歴と元のユーザー発言を引き継ぐ', (await c.cmd('loadSession', { sessionId: id })).messages.filter(m => m.role === 'user').map(m => m.text).join('|') === 'echo:first|slow|continue');
    const changedDir = path.join(dataDir, 'next-work');
    await fs.mkdir(changedDir);
    await c.cmd('setTurnSettings', { sessionId: id, cwd: changedDir });
    const codexDir = await c.runTurn({ sessionId: id, prompt: 'continue in new directory' });
    t.ok('Codex の再開ターンにも作業場所を渡す', codexDir.events.some(e => e.type === 'tool.start' && e.input?.cwd === changedDir));
    const { sessionId: dirId } = await c.cmd('newSession', { backend: 'fake' });
    await c.cmd('setTurnSettings', { sessionId: dirId, cwd: ROOT });
    const dirMark = c.mark();
    await c.cmd('runTurn', { sessionId: dirId, prompt: 'slow' });
    await c.cmd('setTurnSettings', { sessionId: dirId, cwd: changedDir });
    await c.cmd('setTurnSettings', { sessionId: dirId, model: 'smart' });
    t.ok('モデル予約を重ねても作業場所の予約を保持', (await row(dirId)).nextSettings?.cwd === changedDir);
    t.ok('実行中の作業場所は変わらない', (await c.cmd('running')).turns.find(x => x.sessionId === dirId).cwd === ROOT && (await row(dirId)).cwd === ROOT);
    await c.cmd('setTurnSettings', { sessionId: dirId, cwd: ROOT });
    t.ok('作業場所を元に戻してもモデル予約は保持', !(await row(dirId)).nextSettings?.cwd && (await row(dirId)).nextSettings?.model === 'smart');
    await c.cmd('setTurnSettings', { sessionId: dirId, cancel: true });
    t.ok('作業場所を含めた予約を取り消す', !(await row(dirId)).nextSettings);
    await c.cmd('setTurnSettings', { sessionId: dirId, cwd: changedDir });
    for (const cwd of ['', path.join(dataDir, 'missing'), path.join(ROOT, 'package.json')]) {
      await c.cmd('setTurnSettings', { sessionId: dirId, cwd }).then(() => t.ok('不正な作業場所を拒否', false), () => t.ok('不正な作業場所を拒否', true));
    }
    t.ok('不正な変更でも以前の予約を保持', (await row(dirId)).nextSettings?.cwd === changedDir);
    await c.cmd('abort', { sessionId: dirId }); await c.waitFor(e => e.type === 'turnEnd' && e.sessionId === dirId, { from: dirMark });
    c.close(); await server.stop(); server = await startServer(config); c = await open({ port: server.port, token: server.token, autoAllow: true });
    t.ok('作業場所の予約を再起動後に復元', (await row(dirId)).nextSettings?.cwd === changedDir && (await row(dirId)).cwd === ROOT);
    await fs.rmdir(changedDir);
    await c.cmd('runTurn', { sessionId: dirId, prompt: 'echo:gone' }).then(() => t.ok('送信前に消えた作業場所を拒否', false), () => t.ok('送信前に消えた作業場所を拒否', true));
    t.ok('送信準備失敗でも作業場所の予約を保持', (await row(dirId)).nextSettings?.cwd === changedDir && (await row(dirId)).cwd === ROOT);
    await fs.mkdir(changedDir);
    await c.runTurn({ sessionId: dirId, cwd: ROOT, prompt: 'echo:changed' });
    t.ok('次のターンで予約場所を優先して適用', (await row(dirId)).cwd === changedDir && !(await row(dirId)).nextSettings);
    // Different global preferences must not replace the choices of the source conversation.
    await c.cmd('setMode', { sessionId: dirId, mode: 'auto' });
    await c.cmd('setModel', { sessionId: dirId, model: '' });
    await c.cmd('setPref', { key: 'backend', value: 'codex' });
    await c.cmd('setPref', { key: 'model', value: 'fast', backend: 'fake' });
    await c.cmd('setPref', { key: 'mode', value: 'default', backend: 'fake' });
    const inherited = await c.cmd('newSession', { sourceSessionId: dirId, cwd: ROOT });
    const inheritedRow = await row(inherited.sessionId);
    t.ok('new session uses source settings over global preferences', inheritedRow.backend === 'fake' && inheritedRow.model === '' && inheritedRow.mode === 'auto');
    const inheritedTurn = await c.runTurn({ sessionId: inherited.sessionId, prompt: 'echo:inherited' });
    t.ok('explicit default model survives different global preference at execution', inheritedTurn.events.some(e => e.type === 'session' && e.model === ''));
    await c.cmd('setTurnSettings', { sessionId: dirId, model: 'smart' });
    const reservedNew = await c.cmd('newSession', { sourceSessionId: dirId, cwd: ROOT });
    t.ok('new session inherits reserved model', (await row(reservedNew.sessionId)).model === 'smart');
    const fork = await c.cmd('fork', { sessionId: dirId });
    let forkRow = await row(fork.sessionId);
    t.ok('fork inherits current settings and reservation', forkRow.backend === 'fake' && forkRow.model === '' && forkRow.mode === 'auto' && forkRow.nextSettings?.model === 'smart');
    await c.cmd('setTurnSettings', { sessionId: dirId, cancel: true });
    await c.cmd('setMode', { sessionId: dirId, mode: 'default' });
    t.ok('source changes do not mutate fork snapshot', (await row(fork.sessionId)).mode === 'auto' && (await row(fork.sessionId)).nextSettings?.model === 'smart');
    c.close(); await server.stop(); server = await startServer(config); c = await open({ port: server.port, token: server.token, autoAllow: true });
    forkRow = await row(fork.sessionId);
    t.ok('fork settings survive restart', forkRow.mode === 'auto' && forkRow.nextSettings?.model === 'smart');
    const forkTurn = await c.runTurn({ sessionId: fork.sessionId, prompt: 'echo:fork settings' });
    t.ok('fork executes with inherited reservation and mode', forkTurn.initModel === 'smart' && (await row(fork.sessionId)).mode === 'auto');
    await c.cmd('setTurnSettings', { sessionId: fork.sessionId, backend: 'codex', model: 'fake-model-2' });
    t.ok('変更先の保存済み承認モードを予約', (await row(fork.sessionId)).nextSettings?.mode === 'readonly');
    await c.cmd('setTurnSettings', { sessionId: fork.sessionId, mode: 'ask' });
    c.close(); await server.stop(); server = await startServer(config); c = await open({ port: server.port, token: server.token, autoAllow: true });
    t.ok('承認モード予約を再起動後に復元', (await row(fork.sessionId)).nextSettings?.mode === 'ask');
    const switchedNew = await c.cmd('newSession', { sourceSessionId: fork.sessionId, cwd: ROOT });
    t.ok('new session inherits reserved agent and its model', (await row(switchedNew.sessionId)).backend === 'codex' && (await row(switchedNew.sessionId)).model === 'fake-model-2');
    t.ok('新規セッションは変更先に予約した承認モードを継承', (await row(switchedNew.sessionId)).mode === 'ask');
    await c.cmd('setTurnSettings', { sessionId: fork.sessionId, backend: 'fake', model: 'smart' });
    t.ok('元のエージェントへ戻すと変更先の承認モードを破棄', !(await row(fork.sessionId)).nextSettings && (await row(fork.sessionId)).mode === 'auto');
    await c.cmd('setTurnSettings', { sessionId: fork.sessionId, backend: 'codex' });
    await c.cmd('setTurnSettings', { sessionId: fork.sessionId, cancel: true });
    t.ok('取り消しは元の承認モードを保持', !(await row(fork.sessionId)).nextSettings && (await row(fork.sessionId)).mode === 'auto');
    const empty = await c.cmd('newSession', { backend: 'fake', cwd: ROOT });
    await c.cmd('deleteUnsentSession', empty);
    t.ok('未送信セッションを明示的に削除', !(await row(empty.sessionId)));
    await c.cmd('deleteUnsentSession', { sessionId: id }).then(() => t.ok('送信済みを誤削除しない', false), () => t.ok('送信済みを誤削除しない', true));
  } finally { c.close(); await server.stop(); }
}
