import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createVisualizationCollector, prepareVisualization, MAX_VISUALIZE_BYTES } from '../../core/visualize.mjs';
import { visualizeReferences, VISUALIZE_START as S, VISUALIZE_END as E, withoutVisualizeReferences } from '../../web/visualize-reference.mjs';
import { renderPresent, renderAssistantMarkdown, renderMarkdown } from '../../web/render.mjs';
import { buildItems } from '../../web/timeline.mjs';
export const name = 'visualize';
export const title = '参照形式・許可パス・スナップショット・旧HTMLの隔離';
export default async function(t) {
  const dir = await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(), 'ply-visual-')));
  const file = path.join(dir, 'chart.html');
  const ref = `${S}${JSON.stringify({ path: file, title: '比較', mode: 'wide' })}${E}`;
  try {
    await fs.writeFile(file, '<button onclick="this.textContent=2">1</button>');
    assert.equal(visualizeReferences(ref).length, 1);
    assert.equal(visualizeReferences('visualize'+JSON.stringify({path:file}))[0].value.path, file);
    assert.equal(visualizeReferences('```text\n'+ref+'\n```').length, 0);
    assert.equal(visualizeReferences('`'+ref+'`').length, 0);
    assert.equal(visualizeReferences('    '+ref).length, 0);
    assert.equal(withoutVisualizeReferences('before\n'+ref+'\nafter'), 'before\n\nafter');
    assert(!renderAssistantMarkdown(ref).includes('visualize'));
    assert(renderAssistantMarkdown(ref, []).includes('visualize'));
    assert(renderMarkdown(ref).includes('visualize'));
    t.ok('コード例・人間の本文は保持し、実際の参照だけ消費', true);
    const saved = [], collector = createVisualizationCollector({ roots: [dir], publish: p => saved.push(p) });
    for (const text of ref.match(/[\s\S]{1,3}/g)) collector.accept({ type: 'text.delta', text });
    collector.accept({ type: 'text.end' }); await collector.close(); await collector.close();
    await fs.writeFile(file, 'changed');
    assert.equal(saved.length, 1); assert(saved[0].content.includes('<button'));
    assert.equal(saved[0].mode, 'wide');
    t.ok('分割された参照を1回だけ取り込み、元ファイルの変更から独立', true);
    const outside = { value: { path: path.join(dir, '../secret.html') } };
    await assert.rejects(prepareVisualization(outside, [dir]));
    await assert.rejects(prepareVisualization({ value: { path: 'relative.html' } }, [dir]));
    await fs.writeFile(file, 'x'.repeat(MAX_VISUALIZE_BYTES + 1));
    await assert.rejects(prepareVisualization({ value: { path: file } }, [dir]));
    const bad = createVisualizationCollector({ roots: [dir], publish: p => saved.push(p) });
    bad.accept({ type: 'text.delta', text: `${S}{"path":true}${E}` }); await bad.close();
    assert(saved.at(-1).error);
    t.ok('不正参照・作業場外・相対パス・サイズ超過を拒否し、エラーを可視化', true);
    const old = renderPresent({ kind: 'html', content: '<script>bad()</script>' });
    const visual = renderPresent(saved[0]);
    assert.equal(old.querySelector('iframe').getAttribute('sandbox'), '');
    assert.equal(visual.querySelector('iframe').getAttribute('sandbox'), 'allow-scripts');
    assert(visual.querySelector('iframe').srcdoc.includes("connect-src 'none'"));
    t.ok('既存HTMLは静的なまま、新しい図だけopaque sandboxで実行', true);
    const messages = [{role:'assistant',text:ref,uuid:'a'}, {role:'user',text:'次'}, {role:'assistant',text:ref,uuid:'b'}];
    const items = buildItems(messages, [saved[0], saved[0]]);
    assert.deepEqual(items.map(i=>i.kind), ['msg','present','msg','msg','present']);
    t.ok('時刻がない履歴でも更新ごとに対応する回答の直後に配置', true);
  } finally { await fs.rm(dir, {recursive:true,force:true}); }
}
