// 絵文字の一覧（グループのアイコン選択に使う）。外部依存を持たないので同梱する。
// 生成: scratchpad の gen-emoji.py（英語は Unicode の名前 + 追加語、日本語は手書き）。
// 1363 個、8 カテゴリ。1 件 = [絵文字, 英語の語, 日本語の語]。検索は両方の語に対する部分一致。
export const CATEGORIES = [
  { id: "smileys", label: "スマイリーと人", icon: "😀", items: [
    ["😀", "grinning face smile happy", "笑顔 にこにこ 笑い"],
    ["😃", "smiling face with open mouth smile happy", "笑顔 うれしい"],
    ["😄", "smiling face with open mouth and smiling eyes smile happy", "笑顔 うれしい"],
    ["😁", "grinning face with smiling eyes grin", "にやり 笑顔"],
    ["😆", "smiling face with open mouth and tightly-closed eyes laugh", "大笑い"],
    ["😅", "smiling face with open mouth and cold sweat sweat", "冷や汗 笑い"],
    ["🤣", "rolling on the floor laughing lol rofl", "爆笑"],
    ["😂", "face with tears of joy joy lol", "泣き笑い 爆笑"],
    ["🙂", "slightly smiling face smile", "微笑み"],
    ["🙃", "upside-down face upside", "逆さ ひねり"],
    ["😉", "winking face wink", "ウインク"],
    ["😊", "smiling face with smiling eyes blush", "照れ笑い にこにこ"],
    ["😇", "smiling face with halo angel halo", "天使 純真"],
    ["🥰", "smiling face with smiling eyes and three hearts love", "大好き ハート"],
    ["😍", "smiling face with heart-shaped eyes love heart", "ハート目 大好き"],
    ["🤩", "grinning face with star eyes star wow", "星目 感動"],
    ["😘", "face throwing a kiss kiss", "投げキス"],
    ["😗", "kissing face kiss", "キス"],
    ["😚", "kissing face with closed eyes kiss", "キス"],
    ["😙", "kissing face with smiling eyes kiss", "キス"],
    ["🥲", "smiling face with tear tear", "泣き笑い ほろり"],
    ["😋", "face savouring delicious food yum", "おいしい"],
    ["😛", "face with stuck-out tongue tongue", "舌 べー"],
    ["😜", "face with stuck-out tongue and winking eye tongue wink", "ウインク 舌"],
    ["🤪", "grinning face with one large and one small eye crazy zany", "おどけ"],
    ["😝", "face with stuck-out tongue and tightly-closed eyes tongue", "舌 目閉じ"],
    ["🤑", "money-mouth face money rich", "お金 金持ち"],
    ["🤗", "hugging face hug", "ハグ 抱擁"],
    ["🤭", "smiling face with smiling eyes and hand covering mouth giggle oops", "口を隠す くすくす"],
    ["🤫", "face with finger covering closed lips shh quiet secret", "しーっ 静かに"],
    ["🤔", "thinking face think hmm", "考える 思案"],
    ["🤐", "zipper-mouth face zip secret", "口チャック 秘密"],
    ["🤨", "face with one eyebrow raised suspicious", "疑い 眉"],
    ["😐", "neutral face neutral", "無表情"],
    ["😑", "expressionless face expressionless", "無表情 うんざり"],
    ["😶", "face without mouth silent", "無言 沈黙"],
    ["😏", "smirking face smirk", "にやり ドヤ"],
    ["😒", "unamused face unamused", "不満 つまらない"],
    ["🙄", "face with rolling eyes eyeroll", "呆れ 目を回す"],
    ["😬", "grimacing face grimace awkward", "気まずい"],
    ["🤥", "lying face lie", "嘘 ピノキオ"],
    ["😌", "relieved face relieved", "安心 ほっ"],
    ["😔", "pensive face sad pensive", "しょんぼり 落ち込み"],
    ["😪", "sleepy face sleepy", "眠い"],
    ["🤤", "drooling face drool", "よだれ"],
    ["😴", "sleeping face sleep zzz", "寝る 睡眠"],
    ["😷", "face with medical mask mask sick", "マスク 病気"],
    ["🤒", "face with thermometer sick fever", "熱 病気"],
    ["🤕", "face with head-bandage injured bandage", "けが 包帯"],
    ["🤢", "nauseated face nausea sick", "吐き気"],
    ["🤮", "face with open mouth vomiting vomit", "嘔吐"],
    ["🤧", "sneezing face sneeze", "くしゃみ 風邪"],
    ["🥵", "overheated face hot", "暑い"],
    ["🥶", "freezing face cold freezing", "寒い"],
    ["🥴", "face with uneven eyes and wavy mouth woozy dizzy", "ふらふら 酔い"],
    ["😵", "dizzy face dizzy", "めまい"],
    ["🤯", "shocked face with exploding head mindblown", "爆発 驚き"],
    ["🤠", "face with cowboy hat cowboy", "カウボーイ"],
    ["🥳", "face with party horn and party hat party celebrate", "パーティー お祝い"],
    ["🥸", "disguised face disguise", "変装"],
    ["😎", "smiling face with sunglasses cool sunglasses", "サングラス クール"],
    ["🤓", "nerd face nerd", "メガネ オタク"],
    ["🧐", "face with monocle monocle inspect", "モノクル 検分"],
    ["😕", "confused face confused", "困惑"],
    ["😟", "worried face worried", "心配"],
    ["🙁", "slightly frowning face frown", "しかめ面"],
    ["☹️", "white frowning face frown", "しかめ面"],
    ["😮", "face with open mouth surprised wow", "驚き"],
    ["😯", "hushed face hushed", "驚き"],
    ["😲", "astonished face astonished", "びっくり"],
    ["😳", "flushed face flushed", "赤面 照れ"],
    ["🥺", "face with pleading eyes pleading puppy", "お願い うるうる"],
    ["😦", "frowning face with open mouth frown", "しかめ面"],
    ["😧", "anguished face anguished", "苦悩"],
    ["😨", "fearful face fear scared", "恐怖"],
    ["😰", "face with open mouth and cold sweat anxious sweat", "不安 冷や汗"],
    ["😥", "disappointed but relieved face sad", "悲しい 安堵"],
    ["😢", "crying face cry tear", "泣く 涙"],
    ["😭", "loudly crying face cry sob", "大泣き"],
    ["😱", "face screaming in fear scream", "叫び 恐怖"],
    ["😖", "confounded face confounded", "困った"],
    ["😣", "persevering face persevere", "我慢"],
    ["😞", "disappointed face disappointed", "落胆"],
    ["😓", "face with cold sweat sweat", "冷や汗 がっかり"],
    ["😩", "weary face weary", "疲れた"],
    ["😫", "tired face tired", "疲れた"],
    ["🥱", "yawning face yawn", "あくび"],
    ["😤", "face with look of triumph triumph huff", "鼻息 怒り"],
    ["😡", "pouting face angry rage", "怒り 激怒"],
    ["😠", "angry face angry", "怒り"],
    ["🤬", "serious face with symbols covering mouth cursing swear", "罵り 怒り"],
    ["😈", "smiling face with horns devil", "悪魔 いたずら"],
    ["👿", "imp devil", "悪魔"],
    ["💀", "skull skull dead", "ドクロ 死"],
    ["☠️", "skull and crossbones skull danger", "ドクロ 危険"],
    ["💩", "pile of poo poop", "うんち"],
    ["🤡", "clown face clown", "ピエロ"],
    ["👹", "japanese ogre ogre", "鬼"],
    ["👺", "japanese goblin goblin", "天狗"],
    ["👻", "ghost ghost", "おばけ 幽霊"],
    ["👽", "extraterrestrial alien alien", "宇宙人"],
    ["🤖", "robot face robot bot", "ロボット"],
    ["😺", "smiling cat face with open mouth cat", "猫 笑顔"],
    ["😸", "grinning cat face with smiling eyes cat", "猫 笑顔"],
    ["😹", "cat face with tears of joy cat", "猫 泣き笑い"],
    ["😻", "smiling cat face with heart-shaped eyes cat love", "猫 ハート目"],
    ["😼", "cat face with wry smile cat", "猫 にやり"],
    ["😽", "kissing cat face with closed eyes cat", "猫 キス"],
    ["🙀", "weary cat face cat", "猫 驚き"],
    ["😿", "crying cat face cat", "猫 泣く"],
    ["😾", "pouting cat face cat", "猫 怒り"],
    ["🙈", "see-no-evil monkey monkey", "見ざる 猿"],
    ["🙉", "hear-no-evil monkey monkey", "聞かざる 猿"],
    ["🙊", "speak-no-evil monkey monkey", "言わざる 猿"],
    ["💋", "kiss mark kiss lips", "キスマーク"],
    ["💌", "love letter love letter", "ラブレター"],
    ["💘", "heart with arrow heart arrow", "矢 ハート"],
    ["💝", "heart with ribbon heart gift", "リボン ハート"],
    ["💖", "sparkling heart heart sparkle", "きらきら ハート"],
    ["💗", "growing heart heart", "ハート 成長"],
    ["💓", "beating heart heartbeat", "鼓動 ハート"],
    ["💞", "revolving hearts hearts", "回る ハート"],
    ["💕", "two hearts hearts", "ふたつ ハート"],
    ["💟", "heart decoration heart", "ハート 飾り"],
    ["❣️", "heavy heart exclamation mark ornament heart", "ハート びっくり"],
    ["💔", "broken heart broken heart", "失恋 ハート"],
    ["❤️", "heavy black heart heart love", "ハート 赤"],
    ["🧡", "orange heart heart", "ハート オレンジ"],
    ["💛", "yellow heart heart", "ハート 黄色"],
    ["💚", "green heart heart", "ハート 緑"],
    ["💙", "blue heart heart", "ハート 青"],
    ["💜", "purple heart heart", "ハート 紫"],
    ["🖤", "black heart heart", "ハート 黒"],
    ["🤍", "white heart heart", "ハート 白"],
    ["🤎", "brown heart heart", "ハート 茶色"],
    ["💯", "hundred points symbol 100 perfect", "百点 満点"],
    ["💢", "anger symbol anger", "怒り マーク"],
    ["💥", "collision symbol boom explosion", "爆発 衝突"],
    ["💫", "dizzy symbol dizzy star", "めまい 星"],
    ["💦", "splashing sweat symbol sweat splash", "汗 水しぶき"],
    ["💨", "dash symbol dash wind", "ダッシュ 風"],
    ["🕳️", "hole hole", "穴"],
    ["💬", "speech balloon speech comment chat", "吹き出し 会話"],
    ["👁️‍🗨️", "eye left speech bubble witness", "目 吹き出し"],
    ["🗨️", "left speech bubble speech", "吹き出し 左"],
    ["🗯️", "right anger bubble anger speech", "怒り 吹き出し"],
    ["💭", "thought balloon thought", "思考 吹き出し"],
    ["💤", "sleeping symbol sleep zzz", "睡眠 zzz"],
    ["👋", "waving hand sign wave hi bye", "手を振る バイバイ"],
    ["🤚", "raised back of hand hand", "手のひら"],
    ["🖐️", "raised hand with fingers splayed hand", "手 五本指"],
    ["✋", "raised hand hand stop", "手 ストップ"],
    ["🖖", "raised hand with part between middle and ring fingers vulcan spock", "バルカン"],
    ["👌", "ok hand sign ok", "OK 了解"],
    ["🤌", "pinched fingers pinch", "つまむ"],
    ["🤏", "pinching hand pinch small", "ちょっと"],
    ["✌️", "victory hand peace victory", "ピース"],
    ["🤞", "hand with index and middle fingers crossed fingers crossed luck", "指を交差 祈る"],
    ["🤟", "i love you hand sign love hand", "愛してる 手"],
    ["🤘", "sign of the horns rock", "ロック 手"],
    ["🤙", "call me hand call", "電話 手"],
    ["👈", "white left pointing backhand index left point", "左 指差し"],
    ["👉", "white right pointing backhand index right point", "右 指差し"],
    ["👆", "white up pointing backhand index up point", "上 指差し"],
    ["🖕", "reversed hand with middle finger extended middle finger", "中指"],
    ["👇", "white down pointing backhand index down point", "下 指差し"],
    ["☝️", "white up pointing index up point", "人差し指 上"],
    ["👍", "thumbs up sign thumbs up good yes", "いいね 賛成"],
    ["👎", "thumbs down sign thumbs down bad no", "だめ 反対"],
    ["✊", "raised fist fist", "こぶし"],
    ["👊", "fisted hand sign punch fist", "パンチ こぶし"],
    ["🤛", "left-facing fist fist", "左 こぶし"],
    ["🤜", "right-facing fist fist", "右 こぶし"],
    ["👏", "clapping hands sign clap", "拍手"],
    ["🙌", "person raising both hands in celebration raised hands hooray", "万歳 両手"],
    ["👐", "open hands sign open hands", "両手 開く"],
    ["🤲", "palms up together palms", "両手 差し出す"],
    ["🤝", "handshake handshake deal", "握手 合意"],
    ["🙏", "person with folded hands pray please thanks", "祈り お願い ありがとう"],
    ["✍️", "writing hand write", "書く 執筆"],
    ["💅", "nail polish nail", "ネイル マニキュア"],
    ["🤳", "selfie selfie", "自撮り"],
    ["💪", "flexed biceps muscle strong", "力こぶ 筋肉 頑張る"],
    ["🦾", "mechanical arm mechanical arm", "義手 ロボット腕"],
    ["🦿", "mechanical leg mechanical leg", "義足"],
    ["🦵", "leg leg", "脚"],
    ["🦶", "foot foot", "足"],
    ["👂", "ear ear", "耳 聞く"],
    ["🦻", "ear with hearing aid hearing aid", "補聴器"],
    ["👃", "nose nose", "鼻 匂い"],
    ["🧠", "brain brain", "脳 頭脳"],
    ["🫀", "anatomical heart heart organ", "心臓"],
    ["🫁", "lungs lungs", "肺"],
    ["🦷", "tooth tooth", "歯"],
    ["🦴", "bone bone", "骨"],
    ["👀", "eyes eyes look", "目 見る 注目"],
    ["👁️", "eye eye", "目"],
    ["👅", "tongue tongue", "舌"],
    ["👄", "mouth mouth lips", "口 唇"],
    ["👶", "baby baby", "赤ちゃん"],
    ["🧒", "child child", "子供"],
    ["👦", "boy boy", "男の子"],
    ["👧", "girl girl", "女の子"],
    ["🧑", "adult person adult", "人 大人"],
    ["👱", "person with blond hair blond", "金髪"],
    ["👨", "man man", "男性"],
    ["🧔", "bearded person beard", "ひげ"],
    ["👩", "woman woman", "女性"],
    ["🧓", "older adult older", "高齢者"],
    ["👴", "older man old man", "おじいさん"],
    ["👵", "older woman old woman", "おばあさん"],
    ["🙍", "person frowning frown person", "しかめ面 人"],
    ["🙎", "person with pouting face pout", "ふくれ面"],
    ["🙅", "face with no good gesture no gesture", "だめ ×"],
    ["🙆", "face with ok gesture ok gesture", "OK 丸"],
    ["💁", "information desk person information desk", "案内 情報"],
    ["🙋", "happy person raising one hand raise hand", "挙手 質問"],
    ["🧏", "deaf person deaf", "ろう者"],
    ["🙇", "person bowing deeply bow sorry", "お辞儀 謝罪"],
    ["🤦", "face palm facepalm", "顔を覆う やれやれ"],
    ["🤷", "shrug shrug dunno", "肩をすくめる 知らない"],
    ["🧑‍⚕️", "adult staff of aesculapius doctor health", "医者 医療"],
    ["🧑‍🎓", "adult graduation cap student graduate", "学生 卒業"],
    ["🧑‍🏫", "adult school teacher", "先生 教師"],
    ["🧑‍⚖️", "adult scales judge", "裁判官"],
    ["🧑‍🌾", "adult ear of rice farmer", "農家"],
    ["🧑‍🍳", "adult cooking cook chef", "料理人 シェフ"],
    ["🧑‍🔧", "adult wrench mechanic", "整備士"],
    ["🧑‍🏭", "adult factory factory worker", "工場 作業員"],
    ["🧑‍💼", "adult briefcase office worker business", "会社員 ビジネス"],
    ["🧑‍🔬", "adult microscope scientist research", "科学者 研究"],
    ["🧑‍💻", "adult personal computer technologist developer coder", "プログラマー エンジニア 開発"],
    ["🧑‍🎤", "adult microphone singer", "歌手"],
    ["🧑‍🎨", "adult artist palette artist", "画家 アーティスト"],
    ["🧑‍✈️", "adult airplane pilot", "パイロット"],
    ["🧑‍🚀", "adult rocket astronaut", "宇宙飛行士"],
    ["🧑‍🚒", "adult fire engine firefighter", "消防士"],
    ["👮", "police officer police", "警察官"],
    ["🕵️", "sleuth or spy detective investigate", "探偵 調査"],
    ["💂", "guardsman guard", "衛兵"],
    ["🥷", "ninja ninja", "忍者"],
    ["👷", "construction worker construction worker", "建設 作業員 工事"],
    ["🤴", "prince prince", "王子"],
    ["👸", "princess princess", "お姫様"],
    ["👳", "man with turban turban", "ターバン"],
    ["👲", "man with gua pi mao cap", "帽子"],
    ["🧕", "person with headscarf hijab", "ヒジャブ"],
    ["🤵", "man in tuxedo tuxedo", "タキシード"],
    ["👰", "bride with veil bride", "花嫁 ベール"],
    ["🤰", "pregnant woman pregnant", "妊婦"],
    ["🤱", "breast-feeding breastfeeding", "授乳"],
    ["👼", "baby angel angel", "天使 赤ちゃん"],
    ["🎅", "father christmas santa christmas", "サンタ"],
    ["🤶", "mother christmas santa", "サンタ 女性"],
    ["🦸", "superhero superhero", "ヒーロー"],
    ["🦹", "supervillain villain", "悪役"],
    ["🧙", "mage wizard mage", "魔法使い"],
    ["🧚", "fairy fairy", "妖精"],
    ["🧛", "vampire vampire", "吸血鬼"],
    ["🧜", "merperson mermaid", "人魚"],
    ["🧝", "elf elf", "エルフ"],
    ["🧞", "genie genie", "ジーニー"],
    ["🧟", "zombie zombie", "ゾンビ"],
    ["💆", "face massage massage", "マッサージ"],
    ["💇", "haircut haircut", "散髪 美容院"],
    ["🚶", "pedestrian walk", "歩く 徒歩"],
    ["🧍", "standing person stand", "立つ"],
    ["🧎", "kneeling person kneel", "ひざまずく"],
    ["🏃", "runner run", "走る ランニング"],
    ["💃", "dancer dance", "ダンス"],
    ["🕺", "man dancing dance", "ダンス 男性"],
    ["🕴️", "man in business suit levitating levitate suit", "浮く スーツ"],
    ["👯", "woman with bunny ears dancers", "ダンサー うさぎ"],
    ["🧖", "person in steamy room sauna", "サウナ"],
    ["🧗", "person climbing climb", "クライミング"],
    ["🤺", "fencer fencing", "フェンシング"],
    ["🏇", "horse racing horse racing", "競馬"],
    ["⛷️", "skier ski", "スキー"],
    ["🏂", "snowboarder snowboard", "スノーボード"],
    ["🏌️", "golfer golf", "ゴルフ"],
    ["🏄", "surfer surf", "サーフィン"],
    ["🚣", "rowboat rowing", "ボート こぐ"],
    ["🏊", "swimmer swim", "水泳"],
    ["⛹️", "person with ball basketball", "バスケ"],
    ["🏋️", "weight lifter weightlifting gym", "ウェイト 筋トレ"],
    ["🚴", "bicyclist bike cycling", "自転車"],
    ["🚵", "mountain bicyclist mountain bike", "マウンテンバイク"],
    ["🤸", "person doing cartwheel cartwheel gymnastics", "側転 体操"],
    ["🤼", "wrestlers wrestling", "レスリング"],
    ["🤽", "water polo water polo", "水球"],
    ["🤾", "handball handball", "ハンドボール"],
    ["🤹", "juggling juggling", "ジャグリング"],
    ["🧘", "person in lotus position yoga meditate", "ヨガ 瞑想"],
    ["🛀", "bath bath", "お風呂"],
    ["🛌", "sleeping accommodation bed sleep", "寝る ベッド"],
    ["👭", "two women holding hands women holding hands", "女性 手つなぎ"],
    ["👫", "man and woman holding hands couple holding hands", "手つなぎ カップル"],
    ["👬", "two men holding hands men holding hands", "男性 手つなぎ"],
    ["💏", "kiss kiss couple", "キス カップル"],
    ["💑", "couple with heart couple love", "カップル ハート"],
    ["👪", "family family", "家族"],
    ["🗣️", "speaking head in silhouette speaking talk", "話す 発言"],
    ["👤", "bust in silhouette user silhouette", "シルエット 人 ユーザー"],
    ["👥", "busts in silhouette users group", "二人 グループ"],
    ["🫂", "people hugging hug", "ハグ 人"],
    ["👣", "footprints footprints", "足跡"],
  ] },
  { id: "nature", label: "動物と自然", icon: "🌿", items: [
    ["🐵", "monkey face monkey", "猿 顔"],
    ["🐒", "monkey monkey", "猿"],
    ["🦍", "gorilla gorilla", "ゴリラ"],
    ["🦧", "orangutan orangutan", "オランウータン"],
    ["🐶", "dog face dog puppy", "犬 顔"],
    ["🐕", "dog dog", "犬"],
    ["🦮", "guide dog guide dog", "盲導犬"],
    ["🐩", "poodle poodle", "プードル"],
    ["🐺", "wolf face wolf", "オオカミ"],
    ["🦊", "fox face fox", "キツネ"],
    ["🦝", "raccoon raccoon", "アライグマ"],
    ["🐱", "cat face cat kitten", "猫 顔"],
    ["🐈", "cat cat", "猫"],
    ["🦁", "lion face lion", "ライオン"],
    ["🐯", "tiger face tiger", "トラ 顔"],
    ["🐅", "tiger tiger", "トラ"],
    ["🐆", "leopard leopard", "ヒョウ"],
    ["🐴", "horse face horse", "馬 顔"],
    ["🐎", "horse horse", "馬"],
    ["🦄", "unicorn face unicorn", "ユニコーン"],
    ["🦓", "zebra face zebra", "シマウマ"],
    ["🦌", "deer deer", "シカ"],
    ["🦬", "bison bison", "バイソン"],
    ["🐮", "cow face cow", "牛 顔"],
    ["🐂", "ox ox", "雄牛"],
    ["🐃", "water buffalo buffalo", "水牛"],
    ["🐄", "cow cow", "牛"],
    ["🐷", "pig face pig", "豚 顔"],
    ["🐖", "pig pig", "豚"],
    ["🐗", "boar boar", "イノシシ"],
    ["🐽", "pig nose pig nose", "豚の鼻"],
    ["🐏", "ram ram", "羊 雄"],
    ["🐑", "sheep sheep", "羊"],
    ["🐐", "goat goat", "ヤギ"],
    ["🐪", "dromedary camel camel", "ラクダ"],
    ["🐫", "bactrian camel camel", "ラクダ ふたこぶ"],
    ["🦙", "llama llama", "ラマ"],
    ["🦒", "giraffe face giraffe", "キリン"],
    ["🐘", "elephant elephant", "ゾウ"],
    ["🦣", "mammoth mammoth", "マンモス"],
    ["🦏", "rhinoceros rhino", "サイ"],
    ["🦛", "hippopotamus hippo", "カバ"],
    ["🐭", "mouse face mouse", "ネズミ 顔"],
    ["🐁", "mouse mouse", "ネズミ"],
    ["🐀", "rat rat", "ラット"],
    ["🐹", "hamster face hamster", "ハムスター"],
    ["🐰", "rabbit face rabbit bunny", "うさぎ 顔"],
    ["🐇", "rabbit rabbit", "うさぎ"],
    ["🐿️", "chipmunk chipmunk squirrel", "リス"],
    ["🦫", "beaver beaver", "ビーバー"],
    ["🦔", "hedgehog hedgehog", "ハリネズミ"],
    ["🦇", "bat bat", "コウモリ"],
    ["🐻", "bear face bear", "クマ"],
    ["🐻‍❄️", "bear face snowflake polar bear", "シロクマ"],
    ["🐨", "koala koala", "コアラ"],
    ["🐼", "panda face panda", "パンダ"],
    ["🦥", "sloth sloth", "ナマケモノ"],
    ["🦦", "otter otter", "カワウソ"],
    ["🦨", "skunk skunk", "スカンク"],
    ["🦘", "kangaroo kangaroo", "カンガルー"],
    ["🦡", "badger badger", "アナグマ"],
    ["🐾", "paw prints paw prints", "足跡 肉球"],
    ["🦃", "turkey turkey", "七面鳥"],
    ["🐔", "chicken chicken", "ニワトリ"],
    ["🐓", "rooster rooster", "雄鶏"],
    ["🐣", "hatching chick hatching chick", "ひよこ 孵化"],
    ["🐤", "baby chick chick", "ひよこ"],
    ["🐥", "front-facing baby chick chick", "ひよこ"],
    ["🐦", "bird bird", "鳥"],
    ["🐧", "penguin penguin", "ペンギン"],
    ["🕊️", "dove of peace dove peace", "鳩 平和"],
    ["🦅", "eagle eagle", "ワシ"],
    ["🦆", "duck duck", "アヒル カモ"],
    ["🦢", "swan swan", "白鳥"],
    ["🦉", "owl owl", "フクロウ"],
    ["🦤", "dodo dodo", "ドードー"],
    ["🪶", "feather feather", "羽根"],
    ["🦩", "flamingo flamingo", "フラミンゴ"],
    ["🦚", "peacock peacock", "クジャク"],
    ["🦜", "parrot parrot", "オウム"],
    ["🐸", "frog face frog", "カエル"],
    ["🐊", "crocodile crocodile", "ワニ"],
    ["🐢", "turtle turtle", "カメ"],
    ["🦎", "lizard lizard", "トカゲ"],
    ["🐍", "snake snake", "ヘビ"],
    ["🐲", "dragon face dragon", "龍 顔"],
    ["🐉", "dragon dragon", "龍 ドラゴン"],
    ["🦕", "sauropod dinosaur sauropod", "恐竜"],
    ["🦖", "t-rex t-rex dinosaur", "ティラノサウルス 恐竜"],
    ["🐳", "spouting whale whale", "クジラ 潮吹き"],
    ["🐋", "whale whale", "クジラ"],
    ["🐬", "dolphin dolphin", "イルカ"],
    ["🦭", "seal seal", "アザラシ"],
    ["🐟", "fish fish", "魚"],
    ["🐠", "tropical fish tropical fish", "熱帯魚"],
    ["🐡", "blowfish blowfish", "フグ"],
    ["🦈", "shark shark", "サメ"],
    ["🐙", "octopus octopus", "タコ"],
    ["🐚", "spiral shell shell", "貝殻"],
    ["🐌", "snail snail", "カタツムリ"],
    ["🦋", "butterfly butterfly", "蝶"],
    ["🐛", "bug bug caterpillar", "いも虫 バグ"],
    ["🐜", "ant ant", "アリ"],
    ["🐝", "honeybee bee", "ハチ ミツバチ"],
    ["🪲", "beetle beetle bug", "甲虫 バグ"],
    ["🐞", "lady beetle ladybug bug", "テントウムシ バグ"],
    ["🦗", "cricket cricket", "コオロギ"],
    ["🪳", "cockroach cockroach", "ゴキブリ"],
    ["🕷️", "spider spider", "クモ"],
    ["🕸️", "spider web web", "クモの巣"],
    ["🦂", "scorpion scorpion", "サソリ"],
    ["🦟", "mosquito mosquito", "蚊"],
    ["🪰", "fly fly", "ハエ"],
    ["🪱", "worm worm", "ミミズ"],
    ["🦠", "microbe microbe virus germ", "ウイルス 菌"],
    ["💐", "bouquet bouquet", "花束"],
    ["🌸", "cherry blossom cherry blossom sakura", "桜"],
    ["💮", "white flower white flower", "白い花 花丸"],
    ["🏵️", "rosette rosette", "ロゼット"],
    ["🌹", "rose rose", "バラ"],
    ["🥀", "wilted flower wilted", "しおれた花"],
    ["🌺", "hibiscus hibiscus", "ハイビスカス"],
    ["🌻", "sunflower sunflower", "ひまわり"],
    ["🌼", "blossom blossom flower", "花"],
    ["🌷", "tulip tulip", "チューリップ"],
    ["🌱", "seedling seedling sprout", "芽 苗 はじまり"],
    ["🪴", "potted plant potted plant", "鉢植え"],
    ["🌲", "evergreen tree evergreen tree", "常緑樹 木"],
    ["🌳", "deciduous tree tree", "木"],
    ["🌴", "palm tree palm tree", "ヤシの木"],
    ["🌵", "cactus cactus", "サボテン"],
    ["🌾", "ear of rice rice ear", "稲 米"],
    ["🌿", "herb herb leaf", "ハーブ 葉"],
    ["☘️", "shamrock shamrock", "クローバー"],
    ["🍀", "four leaf clover clover luck", "四つ葉 幸運"],
    ["🍁", "maple leaf maple leaf", "紅葉 もみじ"],
    ["🍂", "fallen leaf fallen leaf", "落ち葉"],
    ["🍃", "leaf fluttering in wind leaf wind", "葉 風"],
    ["🍄", "mushroom mushroom", "きのこ"],
    ["🌰", "chestnut chestnut", "栗"],
    ["🦀", "crab crab", "カニ"],
    ["🦞", "lobster lobster", "ロブスター"],
    ["🦐", "shrimp shrimp", "エビ"],
    ["🦑", "squid squid", "イカ"],
    ["🦪", "oyster oyster", "牡蠣"],
    ["🌍", "earth globe europe-africa earth globe", "地球 ヨーロッパ"],
    ["🌎", "earth globe americas earth globe", "地球 アメリカ"],
    ["🌏", "earth globe asia-australia earth globe", "地球 アジア"],
    ["🌐", "globe with meridians globe global web", "地球 グローバル web"],
    ["🪨", "rock rock stone", "岩 石"],
    ["🪵", "wood wood log", "木材 丸太"],
    ["🌑", "new moon symbol new moon", "新月"],
    ["🌒", "waxing crescent moon symbol moon", "三日月"],
    ["🌓", "first quarter moon symbol moon", "半月"],
    ["🌔", "waxing gibbous moon symbol moon", "月"],
    ["🌕", "full moon symbol full moon", "満月"],
    ["🌖", "waning gibbous moon symbol moon", "月"],
    ["🌗", "last quarter moon symbol moon", "半月"],
    ["🌘", "waning crescent moon symbol moon", "月"],
    ["🌙", "crescent moon crescent moon night", "三日月 夜"],
    ["🌚", "new moon with face new moon face", "新月 顔"],
    ["🌛", "first quarter moon with face moon face", "月 顔"],
    ["🌜", "last quarter moon with face moon face", "月 顔"],
    ["🌡️", "thermometer thermometer", "温度計"],
    ["☀️", "black sun with rays sun sunny", "太陽 晴れ"],
    ["🌝", "full moon with face full moon face", "満月 顔"],
    ["🌞", "sun with face sun face", "太陽 顔"],
    ["🪐", "ringed planet planet saturn", "土星 惑星"],
    ["⭐", "white medium star star favorite", "星 お気に入り"],
    ["🌟", "glowing star glowing star", "輝く星"],
    ["🌠", "shooting star shooting star", "流れ星"],
    ["🌌", "milky way milky way galaxy", "天の川 銀河"],
    ["☁️", "cloud cloud", "雲 くもり"],
    ["⛅", "sun behind cloud partly cloudy", "晴れ時々曇り"],
    ["⛈️", "thunder cloud and rain thunderstorm", "雷雨"],
    ["🌤️", "white sun with small cloud sun cloud", "晴れ 雲"],
    ["🌥️", "white sun behind cloud cloud", "曇り"],
    ["🌦️", "white sun behind cloud with rain rain sun", "にわか雨"],
    ["🌧️", "cloud with rain rain", "雨"],
    ["🌨️", "cloud with snow snow", "雪"],
    ["🌩️", "cloud with lightning lightning", "雷"],
    ["🌪️", "cloud with tornado tornado", "竜巻"],
    ["🌫️", "fog fog", "霧"],
    ["🌬️", "wind blowing face wind", "風"],
    ["🌀", "cyclone cyclone", "台風 うずまき"],
    ["🌈", "rainbow rainbow", "虹"],
    ["🌂", "closed umbrella umbrella", "傘 閉じた"],
    ["☂️", "umbrella umbrella", "傘"],
    ["☔", "umbrella with rain drops rain umbrella", "雨 傘"],
    ["⛱️", "umbrella on ground beach umbrella", "ビーチパラソル"],
    ["⚡", "high voltage sign lightning electric fast zap", "稲妻 電気 速い"],
    ["❄️", "snowflake snowflake cold", "雪の結晶 寒い"],
    ["☃️", "snowman snowman", "雪だるま"],
    ["⛄", "snowman without snow snowman", "雪だるま"],
    ["☄️", "comet comet", "彗星"],
    ["🔥", "fire fire flame hot", "火 炎 ホット"],
    ["💧", "droplet droplet water", "水滴 しずく"],
    ["🌊", "water wave wave ocean sea", "波 海"],
  ] },
  { id: "food", label: "食べ物と飲み物", icon: "🍎", items: [
    ["🍇", "grapes grapes", "ぶどう"],
    ["🍈", "melon melon", "メロン"],
    ["🍉", "watermelon watermelon", "スイカ"],
    ["🍊", "tangerine tangerine orange", "みかん オレンジ"],
    ["🍋", "lemon lemon", "レモン"],
    ["🍌", "banana banana", "バナナ"],
    ["🍍", "pineapple pineapple", "パイナップル"],
    ["🥭", "mango mango", "マンゴー"],
    ["🍎", "red apple apple", "りんご 赤"],
    ["🍏", "green apple green apple", "りんご 青"],
    ["🍐", "pear pear", "梨"],
    ["🍑", "peach peach", "桃"],
    ["🍒", "cherries cherries", "さくらんぼ"],
    ["🍓", "strawberry strawberry", "いちご"],
    ["🫐", "blueberries blueberries", "ブルーベリー"],
    ["🥝", "kiwifruit kiwi", "キウイ"],
    ["🍅", "tomato tomato", "トマト"],
    ["🫒", "olive olive", "オリーブ"],
    ["🥥", "coconut coconut", "ココナッツ"],
    ["🥑", "avocado avocado", "アボカド"],
    ["🍆", "aubergine eggplant", "なす"],
    ["🥔", "potato potato", "じゃがいも"],
    ["🥕", "carrot carrot", "にんじん"],
    ["🌽", "ear of maize corn", "とうもろこし"],
    ["🌶️", "hot pepper pepper hot spicy", "唐辛子 辛い"],
    ["🫑", "bell pepper bell pepper", "ピーマン パプリカ"],
    ["🥒", "cucumber cucumber", "きゅうり"],
    ["🥬", "leafy green leafy green", "葉野菜"],
    ["🥦", "broccoli broccoli", "ブロッコリー"],
    ["🧄", "garlic garlic", "にんにく"],
    ["🧅", "onion onion", "玉ねぎ"],
    ["🥜", "peanuts peanuts", "ピーナッツ"],
    ["🫘", "beans beans", "豆"],
    ["🍞", "bread bread", "パン 食パン"],
    ["🥐", "croissant croissant", "クロワッサン"],
    ["🥖", "baguette bread baguette", "バゲット"],
    ["🫓", "flatbread flatbread", "フラットブレッド"],
    ["🥨", "pretzel pretzel", "プレッツェル"],
    ["🥯", "bagel bagel", "ベーグル"],
    ["🥞", "pancakes pancakes", "パンケーキ"],
    ["🧇", "waffle waffle", "ワッフル"],
    ["🧀", "cheese wedge cheese", "チーズ"],
    ["🍖", "meat on bone meat bone", "骨付き肉"],
    ["🍗", "poultry leg poultry leg chicken", "チキン 鶏肉"],
    ["🥩", "cut of meat steak meat", "ステーキ 肉"],
    ["🥓", "bacon bacon", "ベーコン"],
    ["🍔", "hamburger hamburger burger", "ハンバーガー"],
    ["🍟", "french fries fries", "フライドポテト"],
    ["🍕", "slice of pizza pizza", "ピザ"],
    ["🌭", "hot dog hot dog", "ホットドッグ"],
    ["🥪", "sandwich sandwich", "サンドイッチ"],
    ["🌮", "taco taco", "タコス"],
    ["🌯", "burrito burrito", "ブリトー"],
    ["🫔", "tamale tamale", "タマル"],
    ["🥙", "stuffed flatbread pita", "ピタ"],
    ["🧆", "falafel falafel", "ファラフェル"],
    ["🥚", "egg egg", "卵"],
    ["🍳", "cooking cooking fried egg", "目玉焼き 料理"],
    ["🥘", "shallow pan of food pan food", "パエリア 鍋"],
    ["🍲", "pot of food pot stew", "鍋 シチュー"],
    ["🫕", "fondue fondue", "フォンデュ"],
    ["🥣", "bowl with spoon bowl cereal", "ボウル シリアル"],
    ["🥗", "green salad salad", "サラダ"],
    ["🍿", "popcorn popcorn", "ポップコーン"],
    ["🧈", "butter butter", "バター"],
    ["🧂", "salt shaker salt", "塩"],
    ["🥫", "canned food canned food", "缶詰"],
    ["🍱", "bento box bento lunch box", "弁当"],
    ["🍘", "rice cracker rice cracker", "せんべい"],
    ["🍙", "rice ball rice ball onigiri", "おにぎり"],
    ["🍚", "cooked rice rice", "ご飯 米"],
    ["🍛", "curry and rice curry", "カレー"],
    ["🍜", "steaming bowl ramen noodle", "ラーメン"],
    ["🍝", "spaghetti spaghetti pasta", "パスタ スパゲッティ"],
    ["🍠", "roasted sweet potato sweet potato", "焼き芋"],
    ["🍢", "oden oden", "おでん"],
    ["🍣", "sushi sushi", "寿司"],
    ["🍤", "fried shrimp fried shrimp", "エビフライ 天ぷら"],
    ["🍥", "fish cake with swirl design fish cake", "なると"],
    ["🥮", "moon cake moon cake", "月餅"],
    ["🍡", "dango dango", "だんご"],
    ["🥟", "dumpling dumpling", "餃子"],
    ["🥠", "fortune cookie fortune cookie", "フォーチュンクッキー"],
    ["🥡", "takeout box takeout box", "テイクアウト"],
    ["🍦", "soft ice cream soft ice cream", "ソフトクリーム"],
    ["🍧", "shaved ice shaved ice", "かき氷"],
    ["🍨", "ice cream ice cream", "アイスクリーム"],
    ["🍩", "doughnut doughnut donut", "ドーナツ"],
    ["🍪", "cookie cookie", "クッキー"],
    ["🎂", "birthday cake birthday cake", "バースデーケーキ 誕生日"],
    ["🍰", "shortcake cake", "ケーキ ショートケーキ"],
    ["🧁", "cupcake cupcake", "カップケーキ"],
    ["🥧", "pie pie", "パイ"],
    ["🍫", "chocolate bar chocolate", "チョコレート"],
    ["🍬", "candy candy", "キャンディ"],
    ["🍭", "lollipop lollipop", "ロリポップ"],
    ["🍮", "custard custard pudding", "プリン"],
    ["🍯", "honey pot honey", "はちみつ"],
    ["🍼", "baby bottle baby bottle", "哺乳瓶"],
    ["🥛", "glass of milk milk", "牛乳 ミルク"],
    ["☕", "hot beverage coffee break", "コーヒー 休憩"],
    ["🫖", "teapot teapot", "ティーポット"],
    ["🍵", "teacup without handle tea", "お茶 緑茶"],
    ["🍶", "sake bottle and cup sake", "日本酒"],
    ["🍾", "bottle with popping cork champagne celebrate", "シャンパン お祝い"],
    ["🍷", "wine glass wine", "ワイン"],
    ["🍸", "cocktail glass cocktail", "カクテル"],
    ["🍹", "tropical drink tropical drink", "トロピカル ドリンク"],
    ["🍺", "beer mug beer", "ビール"],
    ["🍻", "clinking beer mugs cheers beer", "乾杯 ビール"],
    ["🥂", "clinking glasses cheers clink", "乾杯 シャンパン"],
    ["🥃", "tumbler glass whisky", "ウイスキー"],
    ["🥤", "cup with straw cup straw", "ドリンク ストロー"],
    ["🧋", "bubble tea bubble tea", "タピオカ"],
    ["🧃", "beverage box juice box", "ジュース パック"],
    ["🧉", "mate drink mate", "マテ茶"],
    ["🧊", "ice cube ice cube", "氷"],
    ["🥢", "chopsticks chopsticks", "箸"],
    ["🍽️", "fork and knife with plate plate meal", "食事 皿"],
    ["🍴", "fork and knife fork knife meal", "フォークとナイフ 食事"],
    ["🥄", "spoon spoon", "スプーン"],
    ["🔪", "hocho knife", "包丁 ナイフ"],
    ["🏺", "amphora amphora", "壺"],
  ] },
  { id: "activity", label: "活動", icon: "⚽", items: [
    ["🎃", "jack-o-lantern halloween pumpkin", "ハロウィン かぼちゃ"],
    ["🎄", "christmas tree christmas tree", "クリスマスツリー"],
    ["🎆", "fireworks fireworks", "花火"],
    ["🎇", "firework sparkler sparkler", "線香花火"],
    ["🧨", "firecracker firecracker", "爆竹"],
    ["✨", "sparkles sparkles new shiny", "キラキラ 新しい"],
    ["🎈", "balloon balloon", "風船"],
    ["🎉", "party popper party popper celebrate done", "クラッカー お祝い 完了"],
    ["🎊", "confetti ball confetti celebrate", "紙吹雪 お祝い"],
    ["🎋", "tanabata tree tanabata", "七夕"],
    ["🎍", "pine decoration kadomatsu new year", "門松 正月"],
    ["🎎", "japanese dolls hina dolls", "ひな人形"],
    ["🎏", "carp streamer carp streamer", "こいのぼり"],
    ["🎐", "wind chime wind chime", "風鈴"],
    ["🎑", "moon viewing ceremony moon viewing", "月見"],
    ["🧧", "red gift envelope red envelope", "お年玉"],
    ["🎀", "ribbon ribbon bow", "リボン"],
    ["🎁", "wrapped present gift present", "プレゼント 贈り物"],
    ["🎗️", "reminder ribbon reminder ribbon", "リボン 意識"],
    ["🎟️", "admission tickets ticket admission", "チケット 入場券"],
    ["🎫", "ticket ticket", "チケット"],
    ["🎖️", "military medal medal military", "勲章"],
    ["🏆", "trophy trophy win achievement", "トロフィー 優勝 達成"],
    ["🏅", "sports medal medal", "メダル"],
    ["🥇", "first place medal gold first", "金メダル 一位"],
    ["🥈", "second place medal silver second", "銀メダル 二位"],
    ["🥉", "third place medal bronze third", "銅メダル 三位"],
    ["⚽", "soccer ball soccer football", "サッカー"],
    ["⚾", "baseball baseball", "野球"],
    ["🥎", "softball softball", "ソフトボール"],
    ["🏀", "basketball and hoop basketball", "バスケットボール"],
    ["🏐", "volleyball volleyball", "バレーボール"],
    ["🏈", "american football football", "アメフト"],
    ["🏉", "rugby football rugby", "ラグビー"],
    ["🎾", "tennis racquet and ball tennis", "テニス"],
    ["🥏", "flying disc frisbee", "フリスビー"],
    ["🎳", "bowling bowling", "ボウリング"],
    ["🏏", "cricket bat and ball cricket", "クリケット"],
    ["🏑", "field hockey stick and ball field hockey", "ホッケー"],
    ["🏒", "ice hockey stick and puck ice hockey", "アイスホッケー"],
    ["🥍", "lacrosse stick and ball lacrosse", "ラクロス"],
    ["🏓", "table tennis paddle and ball ping pong table tennis", "卓球 ピンポン"],
    ["🏸", "badminton racquet and shuttlecock badminton", "バドミントン"],
    ["🥊", "boxing glove boxing", "ボクシング"],
    ["🥋", "martial arts uniform martial arts karate", "空手 道着"],
    ["🥅", "goal net goal net", "ゴール"],
    ["⛳", "flag in hole golf flag", "ゴルフ 旗"],
    ["⛸️", "ice skate ice skate", "アイススケート"],
    ["🎣", "fishing pole and fish fishing", "釣り"],
    ["🤿", "diving mask diving", "ダイビング"],
    ["🎽", "running shirt with sash running shirt", "ランニングシャツ"],
    ["🎿", "ski and ski boot ski", "スキー"],
    ["🛷", "sled sled", "そり"],
    ["🥌", "curling stone curling", "カーリング"],
    ["🎯", "direct hit target bullseye goal", "的 ダーツ 目標 ゴール"],
    ["🪀", "yo-yo yo-yo", "ヨーヨー"],
    ["🪁", "kite kite", "凧"],
    ["🎱", "billiards 8 ball billiards", "ビリヤード 8"],
    ["🔮", "crystal ball crystal ball", "水晶玉 占い"],
    ["🪄", "magic wand magic wand", "魔法の杖"],
    ["🧿", "nazar amulet nazar amulet", "お守り"],
    ["🎮", "video game game controller", "ゲーム コントローラー"],
    ["🕹️", "joystick joystick", "ジョイスティック"],
    ["🎰", "slot machine slot machine", "スロット"],
    ["🎲", "game die dice random", "サイコロ ランダム"],
    ["🧩", "jigsaw puzzle piece puzzle piece", "パズル ピース"],
    ["🧸", "teddy bear teddy bear", "テディベア ぬいぐるみ"],
    ["🪅", "pinata pinata", "ピニャータ"],
    ["🪆", "nesting dolls nesting dolls", "マトリョーシカ"],
    ["♠️", "black spade suit spade", "スペード"],
    ["♥️", "black heart suit heart suit", "ハート トランプ"],
    ["♦️", "black diamond suit diamond suit", "ダイヤ トランプ"],
    ["♣️", "black club suit club suit", "クラブ"],
    ["♟️", "black chess pawn chess pawn strategy", "チェス 駒 戦略"],
    ["🃏", "playing card black joker joker", "ジョーカー"],
    ["🀄", "mahjong tile red dragon mahjong", "麻雀"],
    ["🎴", "flower playing cards flower cards", "花札"],
    ["🎭", "performing arts performing arts theater", "演劇 仮面"],
    ["🖼️", "frame with picture picture frame", "額縁 絵画"],
    ["🎨", "artist palette palette art design", "パレット アート デザイン"],
    ["🧵", "spool of thread thread", "糸"],
    ["🪡", "sewing needle needle", "縫い針"],
    ["🧶", "ball of yarn yarn", "毛糸"],
    ["🪢", "knot knot", "結び目"],
    ["🎼", "musical score musical score", "楽譜"],
    ["🎵", "musical note music note", "音符 音楽"],
    ["🎶", "multiple musical notes music notes", "音符 音楽"],
    ["🎙️", "studio microphone studio microphone podcast", "マイク スタジオ"],
    ["🎚️", "level slider level slider", "スライダー レベル"],
    ["🎛️", "control knobs control knobs", "つまみ コントロール"],
    ["🎤", "microphone microphone karaoke", "マイク カラオケ"],
    ["🎧", "headphone headphone", "ヘッドホン"],
    ["📻", "radio radio", "ラジオ"],
    ["🎷", "saxophone saxophone", "サックス"],
    ["🪗", "accordion accordion", "アコーディオン"],
    ["🎸", "guitar guitar", "ギター"],
    ["🎹", "musical keyboard piano keyboard", "ピアノ 鍵盤"],
    ["🎺", "trumpet trumpet", "トランペット"],
    ["🎻", "violin violin", "バイオリン"],
    ["🪕", "banjo banjo", "バンジョー"],
    ["🥁", "drum with drumsticks drum", "ドラム"],
    ["🪘", "long drum long drum", "太鼓"],
    ["🎬", "clapper board clapper movie action", "カチンコ 映画 アクション"],
    ["🎪", "circus tent circus", "サーカス テント"],
  ] },
  { id: "travel", label: "旅行と場所", icon: "🚀", items: [
    ["🚗", "automobile car", "車 自動車"],
    ["🚕", "taxi taxi", "タクシー"],
    ["🚙", "recreational vehicle suv", "SUV"],
    ["🚌", "bus bus", "バス"],
    ["🚎", "trolleybus trolleybus", "トロリーバス"],
    ["🏎️", "racing car racing car fast", "レーシングカー 速い"],
    ["🚓", "police car police car", "パトカー"],
    ["🚑", "ambulance ambulance", "救急車"],
    ["🚒", "fire engine fire engine", "消防車"],
    ["🚐", "minibus minibus", "ミニバン"],
    ["🛻", "pickup truck pickup truck", "ピックアップ"],
    ["🚚", "delivery truck delivery truck", "トラック 配送"],
    ["🚛", "articulated lorry lorry", "トレーラー"],
    ["🚜", "tractor tractor", "トラクター"],
    ["🏍️", "racing motorcycle motorcycle", "バイク オートバイ"],
    ["🛵", "motor scooter scooter", "スクーター"],
    ["🦽", "manual wheelchair manual wheelchair", "車いす 手動"],
    ["🦼", "motorized wheelchair motorized wheelchair", "車いす 電動"],
    ["🛺", "auto rickshaw auto rickshaw", "三輪タクシー"],
    ["🚲", "bicycle bicycle bike", "自転車"],
    ["🛴", "scooter kick scooter", "キックスケーター"],
    ["🛹", "skateboard skateboard", "スケートボード"],
    ["🛼", "roller skate roller skate", "ローラースケート"],
    ["🚏", "bus stop bus stop", "バス停"],
    ["🛣️", "motorway motorway highway", "高速道路"],
    ["🛤️", "railway track railway track", "線路"],
    ["🛢️", "oil drum oil drum", "ドラム缶 オイル"],
    ["⛽", "fuel pump fuel gas", "ガソリンスタンド"],
    ["🚨", "police cars revolving light police light alert emergency", "パトランプ 警告 緊急"],
    ["🚥", "horizontal traffic light traffic light", "信号"],
    ["🚦", "vertical traffic light traffic light", "信号"],
    ["🛑", "octagonal sign stop sign", "停止 ストップ"],
    ["🚧", "construction sign construction wip", "工事中 作業中"],
    ["⚓", "anchor anchor", "錨"],
    ["⛵", "sailboat sailboat", "ヨット 帆船"],
    ["🛶", "canoe canoe", "カヌー"],
    ["🚤", "speedboat speedboat", "スピードボート"],
    ["🛳️", "passenger ship passenger ship", "客船"],
    ["⛴️", "ferry ferry", "フェリー"],
    ["🛥️", "motor boat motor boat", "モーターボート"],
    ["🚢", "ship ship", "船"],
    ["✈️", "airplane airplane flight", "飛行機 出張"],
    ["🛩️", "small airplane small airplane", "小型機"],
    ["🛫", "airplane departure departure takeoff", "離陸 出発"],
    ["🛬", "airplane arriving arrival landing", "着陸 到着"],
    ["🪂", "parachute parachute", "パラシュート"],
    ["💺", "seat seat", "座席"],
    ["🚁", "helicopter helicopter", "ヘリコプター"],
    ["🚟", "suspension railway suspension railway", "モノレール"],
    ["🚠", "mountain cableway cableway", "ロープウェイ"],
    ["🚡", "aerial tramway aerial tramway", "ゴンドラ"],
    ["🛰️", "satellite satellite", "人工衛星"],
    ["🚀", "rocket rocket launch release ship", "ロケット 打ち上げ リリース"],
    ["🛸", "flying saucer ufo flying saucer", "UFO"],
    ["🚂", "steam locomotive locomotive", "機関車"],
    ["🚃", "railway car railway car", "電車 車両"],
    ["🚄", "high-speed train bullet train shinkansen", "新幹線"],
    ["🚅", "high-speed train with bullet nose bullet train", "新幹線"],
    ["🚆", "train train", "電車"],
    ["🚇", "metro metro subway", "地下鉄 メトロ"],
    ["🚈", "light rail light rail", "ライトレール"],
    ["🚉", "station station", "駅"],
    ["🚊", "tram tram", "路面電車"],
    ["🚝", "monorail monorail", "モノレール"],
    ["🚞", "mountain railway mountain railway", "登山鉄道"],
    ["🚋", "tram car tram car", "路面電車"],
    ["🛎️", "bellhop bell bellhop bell", "ベル フロント"],
    ["🧳", "luggage luggage travel", "スーツケース 旅行"],
    ["⌛", "hourglass hourglass done", "砂時計 時間切れ"],
    ["⏳", "hourglass with flowing sand hourglass waiting", "砂時計 待ち 進行中"],
    ["⌚", "watch watch", "腕時計"],
    ["⏰", "alarm clock alarm clock", "目覚まし時計 アラーム"],
    ["⏱️", "stopwatch stopwatch", "ストップウォッチ"],
    ["⏲️", "timer clock timer", "タイマー"],
    ["🕰️", "mantelpiece clock mantelpiece clock", "置き時計"],
    ["🕐", "clock face one oclock clock one", "一時"],
    ["🕑", "clock face two oclock clock two", "二時"],
    ["🕒", "clock face three oclock clock three", "三時"],
    ["🕓", "clock face four oclock clock four", "四時"],
    ["🕔", "clock face five oclock clock five", "五時"],
    ["🕕", "clock face six oclock clock six", "六時"],
    ["🕖", "clock face seven oclock clock seven", "七時"],
    ["🕗", "clock face eight oclock clock eight", "八時"],
    ["🕘", "clock face nine oclock clock nine", "九時"],
    ["🕙", "clock face ten oclock clock ten", "十時"],
    ["🕚", "clock face eleven oclock clock eleven", "十一時"],
    ["🕛", "clock face twelve oclock clock twelve", "十二時"],
    ["🗺️", "world map world map", "世界地図"],
    ["🗾", "silhouette of japan japan map", "日本地図 日本"],
    ["🧭", "compass compass direction", "コンパス 方角"],
    ["🏔️", "snow capped mountain snow mountain", "雪山"],
    ["⛰️", "mountain mountain", "山"],
    ["🌋", "volcano volcano", "火山"],
    ["🗻", "mount fuji mount fuji", "富士山"],
    ["🏕️", "camping camping", "キャンプ"],
    ["🏖️", "beach with umbrella beach", "ビーチ"],
    ["🏜️", "desert desert", "砂漠"],
    ["🏝️", "desert island island", "島"],
    ["🏞️", "national park national park", "国立公園"],
    ["🏟️", "stadium stadium", "スタジアム"],
    ["🏛️", "classical building classical building", "神殿 公共"],
    ["🏗️", "building construction construction crane", "建設中 クレーン"],
    ["🧱", "brick brick", "レンガ 壁"],
    ["🏘️", "house buildings houses", "住宅街"],
    ["🏚️", "derelict house building derelict house", "廃屋"],
    ["🏠", "house building house home", "家 ホーム"],
    ["🏡", "house with garden house garden", "家 庭"],
    ["🏢", "office building office building company", "オフィスビル 会社"],
    ["🏣", "japanese post office post office japan", "郵便局"],
    ["🏤", "european post office post office", "郵便局"],
    ["🏥", "hospital hospital", "病院"],
    ["🏦", "bank bank", "銀行"],
    ["🏨", "hotel hotel", "ホテル"],
    ["🏩", "love hotel love hotel", "ラブホテル"],
    ["🏪", "convenience store convenience store", "コンビニ"],
    ["🏫", "school school", "学校"],
    ["🏬", "department store department store", "デパート"],
    ["🏭", "factory factory", "工場"],
    ["🏯", "japanese castle japanese castle", "城 日本"],
    ["🏰", "european castle castle", "城"],
    ["💒", "wedding wedding", "結婚式"],
    ["🗼", "tokyo tower tokyo tower", "東京タワー"],
    ["🗽", "statue of liberty statue of liberty", "自由の女神"],
    ["⛪", "church church", "教会"],
    ["🕌", "mosque mosque", "モスク"],
    ["🛕", "hindu temple hindu temple", "ヒンドゥー寺院"],
    ["🕍", "synagogue synagogue", "シナゴーグ"],
    ["⛩️", "shinto shrine shrine torii", "鳥居 神社"],
    ["🕋", "kaaba kaaba", "カアバ"],
    ["⛲", "fountain fountain", "噴水"],
    ["⛺", "tent tent", "テント"],
    ["🌁", "foggy foggy", "霧 橋"],
    ["🌃", "night with stars night stars", "夜景 星"],
    ["🏙️", "cityscape cityscape city", "都市 街"],
    ["🌄", "sunrise over mountains sunrise mountains", "日の出 山"],
    ["🌅", "sunrise sunrise morning", "日の出 朝"],
    ["🌆", "cityscape at dusk dusk city", "夕暮れ 街"],
    ["🌇", "sunset over buildings sunset", "夕日"],
    ["🌉", "bridge at night bridge night", "夜 橋"],
    ["♨️", "hot springs hot springs onsen", "温泉"],
    ["🎠", "carousel horse carousel", "メリーゴーランド"],
    ["🎡", "ferris wheel ferris wheel", "観覧車"],
    ["🎢", "roller coaster roller coaster", "ジェットコースター"],
    ["💈", "barber pole barber pole", "床屋"],
  ] },
  { id: "objects", label: "オブジェクト", icon: "💡", items: [
    ["🔇", "speaker with cancellation stroke mute", "消音 ミュート"],
    ["🔈", "speaker speaker", "スピーカー"],
    ["🔉", "speaker with one sound wave volume", "音量"],
    ["🔊", "speaker with three sound waves loud", "大音量"],
    ["📢", "public address loudspeaker loudspeaker announcement", "拡声器 お知らせ"],
    ["📣", "cheering megaphone megaphone announce", "メガホン 告知"],
    ["📯", "postal horn postal horn", "ホルン"],
    ["🔔", "bell bell notification reminder", "ベル 通知 リマインド"],
    ["🔕", "bell with cancellation stroke bell off", "通知オフ"],
    ["📱", "mobile phone phone mobile", "スマホ 携帯"],
    ["📲", "mobile phone with rightwards arrow at left phone arrow", "スマホ 矢印"],
    ["☎️", "black telephone telephone", "電話"],
    ["📞", "telephone receiver phone call", "受話器 電話"],
    ["📟", "pager pager", "ポケベル"],
    ["📠", "fax machine fax", "ファックス"],
    ["🔋", "battery battery", "バッテリー 電池"],
    ["🪫", "low battery low battery", "バッテリー切れ"],
    ["🔌", "electric plug plug power", "プラグ 電源"],
    ["💻", "personal computer laptop computer dev", "ノートパソコン PC 開発"],
    ["🖥️", "desktop computer desktop computer", "デスクトップ PC"],
    ["🖨️", "printer printer", "プリンター"],
    ["⌨️", "keyboard keyboard", "キーボード"],
    ["🖱️", "three button mouse mouse computer", "マウス"],
    ["🖲️", "trackball trackball", "トラックボール"],
    ["💽", "minidisc minidisc", "ディスク"],
    ["💾", "floppy disk floppy save", "フロッピー 保存"],
    ["💿", "optical disc cd disc", "CD ディスク"],
    ["📀", "dvd dvd", "DVD"],
    ["🧮", "abacus abacus calculate", "そろばん 計算"],
    ["🎥", "movie camera movie camera", "映画カメラ"],
    ["🎞️", "film frames film", "フィルム"],
    ["📽️", "film projector projector", "映写機"],
    ["📺", "television tv television", "テレビ"],
    ["📷", "camera camera photo", "カメラ 写真"],
    ["📸", "camera with flash camera flash screenshot", "カメラ フラッシュ スクショ"],
    ["📹", "video camera video camera", "ビデオカメラ"],
    ["📼", "videocassette videocassette", "ビデオテープ"],
    ["🔍", "left-pointing magnifying glass magnifier search investigate", "虫眼鏡 検索 調査"],
    ["🔎", "right-pointing magnifying glass magnifier search", "虫眼鏡 検索"],
    ["🕯️", "candle candle", "ろうそく"],
    ["💡", "electric light bulb light bulb idea", "電球 アイデア ひらめき"],
    ["🔦", "electric torch flashlight", "懐中電灯"],
    ["🏮", "izakaya lantern lantern", "提灯"],
    ["🪔", "diya lamp diya lamp", "ランプ"],
    ["📔", "notebook with decorative cover notebook cover", "ノート 表紙"],
    ["📕", "closed book closed book", "本 赤 閉じた"],
    ["📖", "open book open book read", "本 開いた 読む"],
    ["📗", "green book green book", "本 緑"],
    ["📘", "blue book blue book", "本 青"],
    ["📙", "orange book orange book", "本 オレンジ"],
    ["📚", "books books study docs", "本 積む 資料 学習"],
    ["📓", "notebook notebook", "ノート"],
    ["📒", "ledger ledger", "台帳"],
    ["📃", "page with curl page document", "書類 ページ"],
    ["📜", "scroll scroll", "巻物"],
    ["📄", "page facing up page document", "ページ 文書"],
    ["📰", "newspaper newspaper news", "新聞 ニュース"],
    ["🗞️", "rolled-up newspaper rolled newspaper", "新聞 丸めた"],
    ["📑", "bookmark tabs bookmark tabs", "しおり タブ"],
    ["🔖", "bookmark bookmark", "しおり ブックマーク"],
    ["🏷️", "label label tag", "ラベル タグ"],
    ["💰", "money bag money bag budget", "お金 袋 予算"],
    ["🪙", "coin coin", "コイン"],
    ["💴", "banknote with yen sign yen money", "円 お金"],
    ["💵", "banknote with dollar sign dollar money", "ドル お金"],
    ["💶", "banknote with euro sign euro", "ユーロ"],
    ["💷", "banknote with pound sign pound", "ポンド"],
    ["💸", "money with wings money wings cost", "お金 飛ぶ 出費"],
    ["💳", "credit card credit card payment", "クレジットカード 支払い"],
    ["🧾", "receipt receipt", "レシート 領収書"],
    ["💹", "chart with upwards trend and yen sign chart increasing yen", "チャート 上昇 円"],
    ["✉️", "envelope envelope mail email", "封筒 メール"],
    ["📧", "e-mail symbol email", "メール"],
    ["📨", "incoming envelope incoming envelope", "受信 メール"],
    ["📩", "envelope with downwards arrow above envelope arrow", "メール 矢印"],
    ["📤", "outbox tray outbox send", "送信箱 送る"],
    ["📥", "inbox tray inbox receive", "受信箱 受け取る"],
    ["📦", "package package box delivery", "荷物 パッケージ 配送"],
    ["📫", "closed mailbox with raised flag mailbox", "郵便受け"],
    ["📪", "closed mailbox with lowered flag mailbox empty", "郵便受け 空"],
    ["📬", "open mailbox with raised flag mailbox mail", "郵便受け 受信"],
    ["📭", "open mailbox with lowered flag mailbox", "郵便受け"],
    ["📮", "postbox postbox", "ポスト"],
    ["🗳️", "ballot box with ballot ballot box vote", "投票箱 投票"],
    ["✏️", "pencil pencil write edit", "鉛筆 書く 編集"],
    ["✒️", "black nib pen nib", "ペン先"],
    ["🖋️", "lower left fountain pen fountain pen", "万年筆"],
    ["🖊️", "lower left ballpoint pen pen", "ペン"],
    ["🖌️", "lower left paintbrush paintbrush", "筆 ペイント"],
    ["🖍️", "lower left crayon crayon", "クレヨン"],
    ["📝", "memo memo note write docs", "メモ 書く 記録 ドキュメント"],
    ["💼", "briefcase briefcase work business", "ブリーフケース 仕事 ビジネス"],
    ["📁", "file folder folder file", "フォルダ ファイル"],
    ["📂", "open file folder open folder", "フォルダ 開いた"],
    ["🗂️", "card index dividers card index dividers", "仕切り インデックス"],
    ["📅", "calendar calendar date schedule", "カレンダー 日付 予定"],
    ["📆", "tear-off calendar tear-off calendar", "カレンダー めくり"],
    ["🗒️", "spiral note pad spiral notepad", "メモ帳"],
    ["🗓️", "spiral calendar pad spiral calendar", "カレンダー スパイラル"],
    ["📇", "card index card index", "名刺 インデックス"],
    ["📈", "chart with upwards trend chart increasing growth", "グラフ 上昇 成長"],
    ["📉", "chart with downwards trend chart decreasing", "グラフ 下降"],
    ["📊", "bar chart bar chart stats analytics", "棒グラフ 統計 分析"],
    ["📋", "clipboard clipboard task list", "クリップボード タスク 一覧"],
    ["📌", "pushpin pushpin pin important", "ピン 固定 重要"],
    ["📍", "round pushpin round pushpin location", "位置 場所 ピン"],
    ["📎", "paperclip paperclip attachment", "クリップ 添付"],
    ["🖇️", "linked paperclips linked paperclips", "クリップ 連結"],
    ["📏", "straight ruler ruler measure", "定規 測る"],
    ["📐", "triangular ruler triangular ruler", "三角定規"],
    ["✂️", "black scissors scissors cut", "ハサミ 切る"],
    ["🗃️", "card file box card file box archive", "ファイルボックス アーカイブ"],
    ["🗄️", "file cabinet file cabinet", "キャビネット"],
    ["🗑️", "wastebasket wastebasket trash delete", "ゴミ箱 削除"],
    ["🔒", "lock lock secure", "鍵 ロック 安全"],
    ["🔓", "open lock unlock", "ロック解除"],
    ["🔏", "lock with ink pen lock pen", "鍵 ペン"],
    ["🔐", "closed lock with key closed lock key", "鍵 閉じた"],
    ["🔑", "key key", "鍵 キー"],
    ["🗝️", "old key old key", "古い鍵"],
    ["🔨", "hammer hammer fix build", "ハンマー 修理 作業"],
    ["🪓", "axe axe", "斧"],
    ["⛏️", "pick pick dig", "つるはし 掘る"],
    ["⚒️", "hammer and pick hammer pick", "ハンマーとつるはし"],
    ["🛠️", "hammer and wrench tools settings fix maintenance", "工具 設定 修理 メンテ"],
    ["🗡️", "dagger knife dagger", "短剣"],
    ["⚔️", "crossed swords swords battle", "剣 戦い"],
    ["🔫", "pistol water pistol", "水鉄砲"],
    ["🪃", "boomerang boomerang", "ブーメラン"],
    ["🏹", "bow and arrow bow arrow", "弓矢"],
    ["🛡️", "shield shield security defense", "盾 防御 セキュリティ"],
    ["🪚", "carpentry saw saw", "のこぎり"],
    ["🔧", "wrench wrench settings fix", "レンチ 設定 修理"],
    ["🪛", "screwdriver screwdriver", "ドライバー"],
    ["🔩", "nut and bolt nut bolt", "ボルト ナット"],
    ["⚙️", "gear gear settings config", "歯車 設定 仕組み"],
    ["🗜️", "compression clamp", "万力"],
    ["⚖️", "scales balance scale compare", "天秤 比較 公平"],
    ["🦯", "probing cane white cane", "白杖"],
    ["🔗", "link symbol link connect", "リンク 接続"],
    ["⛓️", "chains chains", "鎖"],
    ["🪝", "hook hook", "フック"],
    ["🧰", "toolbox toolbox", "工具箱"],
    ["🧲", "magnet magnet", "磁石"],
    ["🪜", "ladder ladder", "はしご"],
    ["⚗️", "alembic alembic experiment", "蒸留器 実験"],
    ["🧪", "test tube test tube experiment test", "試験管 実験 テスト"],
    ["🧫", "petri dish petri dish", "シャーレ"],
    ["🧬", "dna double helix dna", "DNA 遺伝子"],
    ["🔬", "microscope microscope research", "顕微鏡 研究 詳細"],
    ["🔭", "telescope telescope explore", "望遠鏡 探索"],
    ["📡", "satellite antenna satellite antenna", "アンテナ 通信"],
    ["💉", "syringe syringe", "注射"],
    ["🩸", "drop of blood blood", "血"],
    ["💊", "pill pill medicine", "薬 錠剤"],
    ["🩹", "adhesive bandage bandage patch fix", "絆創膏 修正 パッチ"],
    ["🩺", "stethoscope stethoscope diagnose", "聴診器 診断"],
    ["🚪", "door door", "ドア"],
    ["🛗", "elevator elevator", "エレベーター"],
    ["🪞", "mirror mirror", "鏡"],
    ["🪟", "window window", "窓"],
    ["🛏️", "bed bed", "ベッド"],
    ["🛋️", "couch and lamp couch", "ソファ"],
    ["🪑", "chair chair", "椅子"],
    ["🚽", "toilet toilet", "トイレ"],
    ["🪠", "plunger plunger", "ラバーカップ"],
    ["🚿", "shower shower", "シャワー"],
    ["🛁", "bathtub bathtub", "浴槽"],
    ["🪤", "mouse trap mouse trap", "ネズミ捕り"],
    ["🪒", "razor razor", "かみそり"],
    ["🧴", "lotion bottle lotion", "ローション"],
    ["🧷", "safety pin safety pin", "安全ピン"],
    ["🧹", "broom broom clean cleanup", "ほうき 掃除 整理"],
    ["🧺", "basket basket", "かご"],
    ["🧻", "roll of paper toilet paper", "トイレットペーパー"],
    ["🪣", "bucket bucket", "バケツ"],
    ["🧼", "bar of soap soap", "石けん"],
    ["🫧", "bubbles bubbles", "泡"],
    ["🪥", "toothbrush toothbrush", "歯ブラシ"],
    ["🧽", "sponge sponge", "スポンジ"],
    ["🧯", "fire extinguisher fire extinguisher", "消火器 緊急"],
    ["🛒", "shopping trolley shopping cart", "カート 買い物"],
    ["🚬", "smoking symbol cigarette", "タバコ"],
    ["⚰️", "coffin coffin", "棺"],
    ["🪦", "headstone headstone", "墓石"],
    ["⚱️", "funeral urn funeral urn", "骨壺"],
    ["🗿", "moyai moai", "モアイ"],
    ["🪧", "placard placard sign", "看板 プラカード"],
    ["👓", "eyeglasses glasses", "メガネ"],
    ["🕶️", "dark sunglasses sunglasses", "サングラス"],
    ["🥽", "goggles goggles", "ゴーグル"],
    ["🥼", "lab coat lab coat", "白衣"],
    ["🦺", "safety vest safety vest", "安全ベスト"],
    ["👔", "necktie necktie work", "ネクタイ 仕事"],
    ["👕", "t-shirt t-shirt", "Tシャツ"],
    ["👖", "jeans jeans", "ジーンズ"],
    ["🧣", "scarf scarf", "マフラー"],
    ["🧤", "gloves gloves", "手袋"],
    ["🧥", "coat coat", "コート"],
    ["🧦", "socks socks", "靴下"],
    ["👗", "dress dress", "ドレス"],
    ["👘", "kimono kimono", "着物"],
    ["🥻", "sari sari", "サリー"],
    ["🩱", "one-piece swimsuit swimsuit", "水着"],
    ["🩲", "briefs briefs", "パンツ"],
    ["🩳", "shorts shorts", "短パン"],
    ["👙", "bikini bikini", "ビキニ"],
    ["👚", "womans clothes blouse", "ブラウス"],
    ["👛", "purse purse", "財布 小銭"],
    ["👜", "handbag handbag", "ハンドバッグ"],
    ["👝", "pouch pouch", "ポーチ"],
    ["🛍️", "shopping bags shopping bags", "ショッピングバッグ 買い物"],
    ["🎒", "school satchel backpack", "リュック"],
    ["🩴", "thong sandal thong sandal", "サンダル ビーチ"],
    ["👞", "mans shoe shoe", "革靴"],
    ["👟", "athletic shoe sneaker running shoe", "スニーカー"],
    ["🥾", "hiking boot hiking boot", "登山靴"],
    ["🥿", "flat shoe flat shoe", "フラットシューズ"],
    ["👠", "high-heeled shoe high heel", "ハイヒール"],
    ["👡", "womans sandal sandal", "サンダル"],
    ["🩰", "ballet shoes ballet", "バレエシューズ"],
    ["👢", "womans boots boot", "ブーツ"],
    ["👑", "crown crown king top", "王冠 トップ"],
    ["👒", "womans hat hat", "帽子 女性"],
    ["🎩", "top hat top hat", "シルクハット"],
    ["🎓", "graduation cap graduation cap learn", "卒業 学位 学習"],
    ["🧢", "billed cap cap", "キャップ"],
    ["🪖", "military helmet military helmet", "ヘルメット 軍"],
    ["⛑️", "helmet with white cross rescue helmet", "ヘルメット 救助"],
    ["📿", "prayer beads prayer beads", "数珠"],
    ["💄", "lipstick lipstick", "口紅"],
    ["💍", "ring ring engagement", "指輪 婚約"],
    ["💎", "gem stone gem diamond valuable", "宝石 ダイヤ 価値"],
  ] },
  { id: "symbols", label: "記号", icon: "✅", items: [
    ["🏧", "automated teller machine atm", "ATM"],
    ["🚮", "put litter in its place symbol litter", "ゴミ箱 記号"],
    ["🚰", "potable water symbol potable water", "飲料水"],
    ["♿", "wheelchair symbol wheelchair accessible", "車いす バリアフリー"],
    ["🚹", "mens symbol mens", "男性用"],
    ["🚺", "womens symbol womens", "女性用"],
    ["🚻", "restroom restroom", "トイレ"],
    ["🚼", "baby symbol baby symbol", "赤ちゃん"],
    ["🚾", "water closet wc", "WC"],
    ["🛂", "passport control passport control", "パスポート"],
    ["🛃", "customs customs", "税関"],
    ["🛄", "baggage claim baggage claim", "手荷物 受取"],
    ["🛅", "left luggage left luggage", "手荷物 預かり"],
    ["⚠️", "warning sign warning caution", "警告 注意"],
    ["🚸", "children crossing children crossing", "子供 横断"],
    ["⛔", "no entry no entry forbidden", "進入禁止 禁止"],
    ["🚫", "no entry sign prohibited no", "禁止 だめ"],
    ["🚳", "no bicycles no bicycles", "自転車禁止"],
    ["🚭", "no smoking symbol no smoking", "禁煙"],
    ["🚯", "do not litter symbol no littering", "ポイ捨て禁止"],
    ["🚱", "non-potable water symbol non-potable", "飲めない"],
    ["🚷", "no pedestrians no pedestrians", "歩行者禁止"],
    ["📵", "no mobile phones no phones", "携帯禁止"],
    ["🔞", "no one under eighteen symbol 18 adults", "18禁"],
    ["☢️", "radioactive sign radioactive", "放射能"],
    ["☣️", "biohazard sign biohazard", "バイオハザード"],
    ["⬆️", "upwards black arrow up arrow", "上 矢印"],
    ["↗️", "north east arrow up-right arrow", "右上 矢印"],
    ["➡️", "black rightwards arrow right arrow next", "右 矢印 次"],
    ["↘️", "south east arrow down-right arrow", "右下 矢印"],
    ["⬇️", "downwards black arrow down arrow", "下 矢印"],
    ["↙️", "south west arrow down-left arrow", "左下 矢印"],
    ["⬅️", "leftwards black arrow left arrow back", "左 矢印 戻る"],
    ["↖️", "north west arrow up-left arrow", "左上 矢印"],
    ["↕️", "up down arrow up-down arrow", "上下 矢印"],
    ["↔️", "left right arrow left-right arrow", "左右 矢印"],
    ["↩️", "leftwards arrow with hook return reply", "戻る 返信"],
    ["↪️", "rightwards arrow with hook forward", "進む"],
    ["⤴️", "arrow pointing rightwards then curving upwards curve up", "上へ曲がる"],
    ["⤵️", "arrow pointing rightwards then curving downwards curve down", "下へ曲がる"],
    ["🔃", "clockwise downwards and upwards open circle arrows refresh clockwise", "更新 時計回り"],
    ["🔄", "anticlockwise downwards and upwards open circle arrows refresh repeat sync loop", "更新 繰り返し 同期"],
    ["🔙", "back with leftwards arrow above back", "戻る BACK"],
    ["🔚", "end with leftwards arrow above end", "終わり END"],
    ["🔛", "on with exclamation mark with left right arrow above on", "ON"],
    ["🔜", "soon with rightwards arrow above soon", "まもなく SOON"],
    ["🔝", "top with upwards arrow above top", "トップ TOP"],
    ["🛐", "place of worship place of worship", "礼拝"],
    ["⚛️", "atom symbol atom science", "原子 科学"],
    ["🕉️", "om symbol om", "オーム"],
    ["✡️", "star of david star of david", "ダビデの星"],
    ["☸️", "wheel of dharma dharma wheel", "法輪"],
    ["☯️", "yin yang yin yang balance", "陰陽 バランス"],
    ["✝️", "latin cross cross", "十字架"],
    ["☦️", "orthodox cross orthodox cross", "正教会 十字"],
    ["☪️", "star and crescent star crescent", "星と月"],
    ["☮️", "peace symbol peace", "ピース 平和"],
    ["🕎", "menorah with nine branches menorah", "メノーラー"],
    ["🔯", "six pointed star with middle dot six pointed star", "六芒星"],
    ["♈", "aries aries", "牡羊座"],
    ["♉", "taurus taurus", "牡牛座"],
    ["♊", "gemini gemini", "双子座"],
    ["♋", "cancer cancer", "蟹座"],
    ["♌", "leo leo", "獅子座"],
    ["♍", "virgo virgo", "乙女座"],
    ["♎", "libra libra", "天秤座"],
    ["♏", "scorpius scorpio", "蠍座"],
    ["♐", "sagittarius sagittarius", "射手座"],
    ["♑", "capricorn capricorn", "山羊座"],
    ["♒", "aquarius aquarius", "水瓶座"],
    ["♓", "pisces pisces", "魚座"],
    ["⛎", "ophiuchus ophiuchus", "蛇遣い座"],
    ["🔀", "twisted rightwards arrows shuffle", "シャッフル"],
    ["🔁", "clockwise rightwards and leftwards open circle arrows repeat loop", "リピート 繰り返し"],
    ["🔂", "clockwise rightwards and leftwards open circle arrows with circled one overlay repeat one", "一曲リピート"],
    ["▶️", "black right-pointing triangle play start run", "再生 開始 実行"],
    ["⏩", "black right-pointing double triangle fast forward", "早送り"],
    ["⏭️", "black right-pointing double triangle with vertical bar next skip", "次へ スキップ"],
    ["⏯️", "black right-pointing triangle with double vertical bar play pause", "再生 一時停止"],
    ["◀️", "black left-pointing triangle reverse back", "逆再生 戻る"],
    ["⏪", "black left-pointing double triangle rewind", "巻き戻し"],
    ["⏮️", "black left-pointing double triangle with vertical bar previous", "前へ"],
    ["🔼", "up-pointing small red triangle up button", "上 三角"],
    ["⏫", "black up-pointing double triangle fast up", "上 二重"],
    ["🔽", "down-pointing small red triangle down button", "下 三角"],
    ["⏬", "black down-pointing double triangle fast down", "下 二重"],
    ["⏸️", "double vertical bar pause hold", "一時停止 保留"],
    ["⏹️", "black square for stop stop", "停止 止める"],
    ["⏺️", "black circle for record record", "録画 記録"],
    ["⏏️", "eject symbol eject", "取り出し"],
    ["🎦", "cinema cinema", "映画館"],
    ["🔅", "low brightness symbol dim", "明るさ 低"],
    ["🔆", "high brightness symbol bright", "明るさ 高"],
    ["📶", "antenna with bars signal antenna bars", "電波 アンテナ"],
    ["📳", "vibration mode vibration", "バイブ"],
    ["📴", "mobile phone off phone off", "電源オフ"],
    ["♀️", "female sign female", "女性 記号"],
    ["♂️", "male sign male", "男性 記号"],
    ["⚧️", "male with stroke and male and female sign transgender", "トランスジェンダー"],
    ["✖️", "heavy multiplication x multiply x", "掛ける ばつ"],
    ["➕", "heavy plus sign plus add new", "プラス 追加 新規"],
    ["➖", "heavy minus sign minus remove", "マイナス 削除 減"],
    ["➗", "heavy division sign divide", "割る"],
    ["🟰", "heavy equals sign equals", "イコール"],
    ["♾️", "permanent paper sign infinity", "無限"],
    ["‼️", "double exclamation mark double exclamation", "二重感嘆"],
    ["⁉️", "exclamation question mark exclamation question", "感嘆 疑問"],
    ["❓", "black question mark ornament question unknown", "疑問 質問 不明"],
    ["❔", "white question mark ornament question", "疑問 白"],
    ["❕", "white exclamation mark ornament exclamation", "感嘆 白"],
    ["❗", "heavy exclamation mark symbol exclamation important", "感嘆 重要 注意"],
    ["〰️", "wavy dash wavy dash", "波線"],
    ["💱", "currency exchange currency exchange", "両替"],
    ["💲", "heavy dollar sign dollar sign", "ドル 記号"],
    ["⚕️", "staff of aesculapius medical", "医療"],
    ["♻️", "black universal recycling symbol recycle reuse", "リサイクル 再利用"],
    ["⚜️", "fleur-de-lis fleur-de-lis", "フルール・ド・リス"],
    ["🔱", "trident emblem trident", "トライデント"],
    ["📛", "name badge name badge", "名札"],
    ["🔰", "japanese symbol for beginner beginner novice", "初心者 若葉"],
    ["⭕", "heavy large circle circle correct ok", "丸 正解 OK"],
    ["✅", "white heavy check mark check done complete", "チェック 完了 済み"],
    ["☑️", "ballot box with check checkbox done", "チェックボックス 済み"],
    ["✔️", "heavy check mark check mark done", "チェック 済み"],
    ["❌", "cross mark cross x fail", "ばつ 失敗 不可"],
    ["❎", "negative squared cross mark cross button", "ばつ 四角"],
    ["➰", "curly loop curly loop", "ループ"],
    ["➿", "double curly loop double curly loop", "二重ループ"],
    ["〽️", "part alternation mark part alternation", "庵点"],
    ["✳️", "eight spoked asterisk eight spoked asterisk", "アスタリスク 八"],
    ["✴️", "eight pointed black star eight pointed star", "星 八"],
    ["❇️", "sparkle sparkle", "きらめき"],
    ["©️", "copyright sign copyright", "著作権"],
    ["®️", "registered sign registered", "登録商標"],
    ["™️", "trade mark sign trademark", "商標"],
    ["#️⃣", "number sign hash number", "シャープ ハッシュ"],
    ["*️⃣", "asterisk asterisk", "アスタリスク"],
    ["0️⃣", "digit zero zero", "ゼロ"],
    ["1️⃣", "digit one one", "いち"],
    ["2️⃣", "digit two two", "に"],
    ["3️⃣", "digit three three", "さん"],
    ["4️⃣", "digit four four", "よん"],
    ["5️⃣", "digit five five", "ご"],
    ["6️⃣", "digit six six", "ろく"],
    ["7️⃣", "digit seven seven", "なな"],
    ["8️⃣", "digit eight eight", "はち"],
    ["9️⃣", "digit nine nine", "きゅう"],
    ["🔟", "keycap ten ten", "じゅう"],
    ["🔠", "input symbol for latin capital letters capital letters", "大文字"],
    ["🔡", "input symbol for latin small letters small letters", "小文字"],
    ["🔢", "input symbol for numbers numbers", "数字"],
    ["🔣", "input symbol for symbols symbols", "記号"],
    ["🔤", "input symbol for latin letters abc letters", "アルファベット"],
    ["🅰️", "negative squared latin capital letter a a", "A 血液型"],
    ["🆎", "negative squared ab ab", "AB 血液型"],
    ["🅱️", "negative squared latin capital letter b b", "B 血液型"],
    ["🆑", "squared cl cl clear", "CL クリア"],
    ["🆒", "squared cool cool", "COOL"],
    ["🆓", "squared free free", "FREE 無料"],
    ["ℹ️", "information source information info", "情報 インフォ"],
    ["🆔", "squared id id", "ID"],
    ["Ⓜ️", "circled latin capital letter m m", "M"],
    ["🆕", "squared new new", "NEW 新着"],
    ["🆖", "squared ng ng", "NG だめ"],
    ["🅾️", "negative squared latin capital letter o o", "O 血液型"],
    ["🆗", "squared ok ok", "OK"],
    ["🅿️", "negative squared latin capital letter p parking", "駐車場"],
    ["🆘", "squared sos sos help", "SOS 助けて"],
    ["🆙", "squared up with exclamation mark up", "UP"],
    ["🆚", "squared vs vs versus", "VS 対決"],
    ["🈁", "squared katakana koko here", "ココ"],
    ["🈂️", "squared katakana sa service", "サービス"],
    ["🈷️", "squared cjk unified ideograph-6708 monthly", "月"],
    ["🈶", "squared cjk unified ideograph-6709 have", "有"],
    ["🈯", "squared cjk unified ideograph-6307 reserved", "指"],
    ["🉐", "circled ideograph advantage bargain", "得 お得"],
    ["🈹", "squared cjk unified ideograph-5272 discount", "割 割引"],
    ["🈚", "squared cjk unified ideograph-7121 free of charge", "無"],
    ["🈲", "squared cjk unified ideograph-7981 prohibited", "禁"],
    ["🉑", "circled ideograph accept accept acceptable", "可 許可"],
    ["🈸", "squared cjk unified ideograph-7533 application", "申 申請"],
    ["🈴", "squared cjk unified ideograph-5408 passing grade", "合 合格"],
    ["🈳", "squared cjk unified ideograph-7a7a vacancy", "空 空き"],
    ["㊗️", "circled ideograph congratulation congratulations", "祝 お祝い"],
    ["㊙️", "circled ideograph secret secret", "秘 秘密"],
    ["🈺", "squared cjk unified ideograph-55b6 open for business", "営 営業中"],
    ["🈵", "squared cjk unified ideograph-6e80 no vacancy", "満 満員"],
    ["🔴", "large red circle red circle", "赤 丸"],
    ["🟠", "large orange circle orange circle", "オレンジ 丸"],
    ["🟡", "large yellow circle yellow circle", "黄色 丸"],
    ["🟢", "large green circle green circle ok", "緑 丸 OK"],
    ["🔵", "large blue circle blue circle", "青 丸"],
    ["🟣", "large purple circle purple circle", "紫 丸"],
    ["🟤", "large brown circle brown circle", "茶色 丸"],
    ["⚫", "medium black circle black circle", "黒 丸"],
    ["⚪", "medium white circle white circle", "白 丸"],
    ["🟥", "large red square red square", "赤 四角"],
    ["🟧", "large orange square orange square", "オレンジ 四角"],
    ["🟨", "large yellow square yellow square", "黄色 四角"],
    ["🟩", "large green square green square", "緑 四角"],
    ["🟦", "large blue square blue square", "青 四角"],
    ["🟪", "large purple square purple square", "紫 四角"],
    ["🟫", "large brown square brown square", "茶色 四角"],
    ["⬛", "black large square black square", "黒 四角"],
    ["⬜", "white large square white square", "白 四角"],
    ["◼️", "black medium square black medium square", "黒 四角 中"],
    ["◻️", "white medium square white medium square", "白 四角 中"],
    ["◾", "black medium small square black small square", "黒 四角 小"],
    ["◽", "white medium small square white small square", "白 四角 小"],
    ["▪️", "black small square black tiny square", "黒 四角 極小"],
    ["▫️", "white small square white tiny square", "白 四角 極小"],
    ["🔶", "large orange diamond orange diamond", "オレンジ ひし形"],
    ["🔷", "large blue diamond blue diamond", "青 ひし形"],
    ["🔸", "small orange diamond small orange diamond", "オレンジ ひし形 小"],
    ["🔹", "small blue diamond small blue diamond", "青 ひし形 小"],
    ["🔺", "up-pointing red triangle red triangle up", "赤 三角 上"],
    ["🔻", "down-pointing red triangle red triangle down", "赤 三角 下"],
    ["💠", "diamond shape with a dot inside diamond shape", "ひし形 花"],
    ["🔘", "radio button radio button", "ラジオボタン"],
    ["🔳", "white square button white square button", "白 四角 ボタン"],
    ["🔲", "black square button black square button", "黒 四角 ボタン"],
  ] },
  { id: "flags", label: "旗", icon: "🏁", items: [
    ["🏁", "chequered flag checkered flag finish done", "チェッカーフラッグ ゴール 完了"],
    ["🚩", "triangular flag on post red flag marker", "赤旗 目印 注意"],
    ["🎌", "crossed flags crossed flags japan", "交差旗 日本"],
    ["🏴", "waving black flag black flag", "黒旗"],
    ["🏳️", "waving white flag white flag", "白旗"],
    ["🏳️‍🌈", "waving white flag rainbow rainbow flag pride", "レインボーフラッグ"],
    ["🏳️‍⚧️", "waving white flag male with stroke and male and female sign transgender flag", "トランスジェンダー 旗"],
    ["🏴‍☠️", "waving black flag skull and crossbones pirate flag", "海賊旗"],
    ["🇯🇵", "japan", "日本"],
    ["🇺🇸", "usa united states", "アメリカ"],
    ["🇬🇧", "uk britain", "イギリス"],
    ["🇨🇳", "china", "中国"],
    ["🇰🇷", "korea", "韓国"],
    ["🇹🇼", "taiwan", "台湾"],
    ["🇩🇪", "germany", "ドイツ"],
    ["🇫🇷", "france", "フランス"],
    ["🇮🇹", "italy", "イタリア"],
    ["🇪🇸", "spain", "スペイン"],
    ["🇨🇦", "canada", "カナダ"],
    ["🇦🇺", "australia", "オーストラリア"],
    ["🇮🇳", "india", "インド"],
    ["🇧🇷", "brazil", "ブラジル"],
    ["🇷🇺", "russia", "ロシア"],
    ["🇸🇬", "singapore", "シンガポール"],
    ["🇹🇭", "thailand", "タイ"],
    ["🇻🇳", "vietnam", "ベトナム"],
    ["🇵🇭", "philippines", "フィリピン"],
    ["🇮🇩", "indonesia", "インドネシア"],
    ["🇲🇾", "malaysia", "マレーシア"],
    ["🇳🇱", "netherlands", "オランダ"],
    ["🇸🇪", "sweden", "スウェーデン"],
    ["🇨🇭", "switzerland", "スイス"],
    ["🇪🇺", "eu europe", "EU ヨーロッパ"],
    ["🇺🇳", "un united nations", "国連"],
  ] },
];

/** 絵文字 1 文字（結合列を含む）を拾う。貼り付けた文字から候補を作るのに使う */
export const EMOJI_RE = /\p{Extended_Pictographic}(?:\uFE0F|\p{Emoji_Modifier})?(?:\u200D\p{Extended_Pictographic}(?:\uFE0F|\p{Emoji_Modifier})?)*|[\p{Regional_Indicator}]{2}|[#*0-9]\uFE0F?\u20E3/gu;
